### ISSUE TITLE
pyfetch: add redirect='follow' default argument 

### ISSUE THREAD

**Issue by henryiii** [pyodide/pyodide#2317] opened 2022-03-25 15:28 UTC
Yes, thanks. I think we should add a redirect='follow' default argument and pass it to JS fetch.

_Originally posted by @rth in https://github.com/pyodide/pyodide/issues/398#issuecomment-1079130371_

**Comment by adphrost** [comment] 2022-05-03 21:21
I'll work on this issue!

**Comment by RulerOfCakes** [comment] 2023-10-22 15:22
> @RulerOfCakes Would you like to work on this issue?

Sure! Although it feels like that the problem originally quoted from [here](https://github.com/pyodide/pyodide/issues/398#issuecomment-1079126866) is caused by something else rather than the absence of a redirect argument. 
Upon trying it out in [pyodide.org/en/stable/console.html](https://pyodide.org/en/stable/console.html), I get the following error:
```
>>> import pyodide.http
>>> inp = await pyodide.http.pyfetch("https://git.io/JJYDE", redirect='follow')
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/lib/python311.zip/pyodide/http.py", line 308, in pyfetch
    raise OSError(e.message) from None
OSError: Failed to fetch
```
oddly enough however, I wasn't able to recreate the error in my local dev/testing environment, as the redirect worked well without a default argument as well.

**Comment by ryanking13** [comment] 2023-10-23 13:31
I talked with @RulerOfCakes and noticed that the problem was not a redirect but a CORS.

- The [default option for `redirect` is `follow`](https://developer.mozilla.org/en-US/docs/Web/API/fetch#redirect), so we don't need to pass it.
- The original issue was due to CORS. The URL `https://git.io/JJYDE` does not set CORS headers, so the request failed.

So, actually, there is nothing we need to do about this issue. Closing as resolved. Thanks for the check @RulerOfCakes!

**Closed by ryanking13** 2023-10-23 13:31 UTC
Labels: Sprint
