### ISSUE TITLE
Flair package request

### ISSUE THREAD

**Issue by atanumandal0491** [pyodide/pyodide#3540] opened 2023-02-03 07:11 UTC
## 🐍 Package Request

- Package Name and Version : Flair
- Package URL : https://github.com/flairNLP/flair
- Package Dependencies that needs to be resolved first:

**Comment by atanumandal0491** [comment] 2023-02-03 07:11
`package:
  name: flair
  version: 0.11.3
  top-level:
    - flair
source:
  sha256: b34b147c4ac2326bff852d582cd0f681b2ffdbc51c3196a4e0029861883cb35c
  url: https://files.pythonhosted.org/packages/52/23/a026b2aa152fcfcd46118b40ae613b92fe74d0ab5e07167612f9cb519206/flair-0.11.3-py3-none-any.whl

about:
  
  license: MIT license
`

**Comment by atanumandal0491** [comment] 2023-02-03 07:12
> `package: name: flair version: 0.11.3 top-level: - flair source: sha256: b34b147c4ac2326bff852d582cd0f681b2ffdbc51c3196a4e0029861883cb35c url: https://files.pythonhosted.org/packages/52/23/a026b2aa152fcfcd46118b40ae613b92fe74d0ab5e07167612f9cb519206/flair-0.11.3-py3-none-any.whl
> 
> about:
> 
> license: MIT license `

meta.yml file

**Comment by rth** [comment] 2023-02-18 10:11
As you noted flair itself is a pure Python package that can be installed via micropip. The issue is that it requires pytorch (see https://github.com/pyodide/pyodide/issues/1625 ) and until that happens there is not much we can do. That's a difficult task and not very likely to happen in the near future (unless someone is willing to work on it). Also some of the other flair dependencies might need porting.

So since this is blocked  by pytorch, I'm going to close this for now, as there is not much we can do about it in this issue. Though don't hesitate to comment further here.

**Closed by rth** 2023-02-18 10:11 UTC
Labels: new package request
