### ISSUE TITLE
 locale.currency() raises ValueError: 'C' locale when setting pt_BR.utf-8 in Pyodide

### ISSUE THREAD

**Issue by vladhietala** [pyodide/pyodide#5234] opened 2024-11-29 00:25 UTC
## 🐛 Bug Report: locale.currency() raises ValueError: 'C' locale when setting pt_BR.utf-8 in Pyodide

The `locale.currency()` function fails in Pyodide even after explicitly setting the locale. The error suggests the system is using 'C' locale instead of the requested "pt_BR.utf-8" locale, indicating a possible issue with locale initialization in the Pyodide environment.

### To Reproduce

```python
import locale

locale.setlocale(locale.LC_ALL, "pt_BR.utf-8")
locale.currency(1459.47, symbol=False, grouping=True)
```
Getting error:
```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/lib/python312.zip/locale.py", line 258, in currency
    raise ValueError("Currency formatting is not possible using "
ValueError: Currency formatting is not possible using the 'C' locale.
```
### Expected behavior

The code should format the number according to Brazilian locale (pt_BR) formatting rules, producing output like "1.459,47".

### Environment

- Pyodide Version: 0.26.4
- Browser: Chrome 131.0.6778.86 (64-bit)
- Testing environment: Pyodide REPL (https://pyodide.org/en/stable/console.html)

### Additional context

![image](https://github.com/user-attachments/assets/164d0298-561d-4e56-87a7-e5801f246d48)

**Comment by ryanking13** [comment] 2024-11-29 07:04
Thanks for the report. I think this is a duplicate of #3915, so I'm closing it as a duplicate, but don't hesitate to comment on that issue.

**Closed by ryanking13** 2024-11-29 07:04 UTC
Labels: bug
