### ISSUE TITLE
out of memory on reload with firefox not chrome

### ISSUE THREAD

**Issue by aliasal** [pyodide/pyodide#610] opened 2020-02-03 11:51 UTC
Hi

I am on Win10, 64bit, newest release, Firefox 72.0.2 (32bit), Chrome 79.0.3945.130 (64-Bit)
I am using Pyodide with a local server that I spin with the attached script:
[pyodide_server.txt](https://github.com/iodide-project/pyodide/files/4147693/pyodide_server.txt)

When I load a test script (Hello World) in Firefox for the first time, everything works fine. 
But when I try to reload it, it gives a "out of memory"  error. I have to restart Firefox to get it going, but that only works one time, then every reload gives that error again.

On Chrome everything works fine.

**Comment by rth** [comment] 2020-02-03 14:07
Just to confirm once you open Firefox, how much free memory would you have remaining (before opening Pyodide)? Before https://github.com/iodide-project/pyodide/pull/600 Pyodide would allocate 1GB of memory per session, and it's possible that it would not be immediately de-allocated with a reload.

**Comment by aliasal** [comment] 2020-02-04 11:18
I checked the memory with Taskmanager (if there is a better, more precise way, please tell me):
I have 16GB in total,
3,2GB used before Pyodide started, 3,6GB after.
Nothing changed on reload, except the  "uncaught exception: out of memory" error.
I have the SysInternals Suite, so if you tell me what to do, I could probably gather more information.

**Comment by aliasal** [comment] 2020-03-13 16:28
This example
https://www.guangshi.io/posts/run-a-random-walker-in-your-website-using-pyodide/
does not work in Firefox, but does so in Chrome.
If I reload it in Firefox I get an "uncaught exception: out of memory" error

**Comment by rth** [comment] 2022-05-01 21:54
Coming back to this issue. I can't reproduce the out-of-memory issue on reload in Firefox. There is a known issue in browsers that reloading tabs don't free memory well, you need to open a new tab instead. We cannot do much about this on our side.

I'm closing this issue as it has been more than two years. If you still experience this issue with recent Pyodide versions, please comment here or open a new issue.

**Closed by rth** 2022-05-01 21:54 UTC
