### ISSUE TITLE
Flaky scipy build

### ISSUE THREAD

**Issue by dalcde** [pyodide/pyodide#936] opened 2020-12-24 01:02 UTC
Recently we are sometimes getting the following error when building scipy
```
Traceback (most recent call last):
  File "setup.py", line 265, in <module>
    setup_package()
  File "setup.py", line 253, in setup_package
    from numpy.distutils.core import setup
ModuleNotFoundError: No module named 'numpy'
```
There have been similar issues with firefox tests too.

**Comment by rth** [comment] 2021-04-20 18:11
From https://github.com/pyodide/pyodide/issues/1508

> We observe that non-interactive builds do not work any longer on 0.17.0 preview

@ondrej-stanek-ozobot This also occasionally happens in CI. Likely a glitch in the multi-threaded build mechanism. It's likely (but not 100% certain) that setting `PYODIDE_JOBS=1` env variable would resolve it (while making the build slower). 

We would need to investigate in more detail. I have re-checked the code recently and haven't seen any obvious parts that could cause this. https://github.com/pyodide/pyodide/issues/1476 would likely be a long term solution.

**Comment by rth** [comment] 2021-04-20 18:22
Another reason for https://github.com/pyodide/pyodide/issues/1476 is that currently it's hard to reproduce and take action on that exception since it happens inside the setup.py installation code not our code.

**Comment by hoodmane** [comment] 2021-04-20 18:29
I thought it would be a quick fix to install numpy with pip on the docker, copy over the host numpy config as we do, then get rid of `skip_host: False`.

Building numpy takes up a significant percentage of the build-packages CI job, both because it is slow itself and because a lot of other slow-building packages have to wait on it. If it works to skip host build that might improve build time quite a lot.

**Comment by rth** [comment] 2021-04-20 18:43
> I thought it would be a quick fix to install numpy with pip on the docker, copy over the host numpy config as we do,

For Docker likely, but that's harder to implement for people installing outside of docker (which we also support) since we then have less control over paths. Also I'm not sure if copying that config would be enough. It would be worth a try.

> Building numpy takes up a significant percentage of the build-packages CI job,

Hmm, so on my laptop installing numpy 1.17.5 from source takes 2min (without ccache). In our build system it should be 2x slower (and then a bit more slower due to CI). Still it shouldn't be that much.

**Comment by hoodmane** [comment] 2021-04-20 18:52
From watching the build-packages job I think building numpy is >50% of the total time. We should add timestamps to the "building pkgname" / "built pkgname" logs so it would be easier to see.

**Comment by rth** [comment] 2021-04-20 20:12
It was 17min to build numpy in https://github.com/pyodide/pyodide/pull/1509 but I think mostly due to CPU oversubscription. It was building numpy, pillow and CLAPACK in parallel where CLAPACK itself created 4 build processes, with only 2CPU available in CI. I reduced parallelism a bit in CI, let's see if that makes the overall build faster. With the setup in that PR numpy builds in 12min now.

Anyway it would still be worth trying to use pre-built numpy.

>  that setting PYODIDE_JOBS=1 env variable would resolve it

Actually that will only be true after https://github.com/pyodide/pyodide/pull/1509 is merged.

**Comment by rth** [comment] 2022-05-01 23:59
I haven't seen this build error for a while. Closing.

**Closed by rth** 2022-05-01 23:59 UTC
Labels: build, CI
