### ISSUE TITLE
ModuleNotFoundError / pkg_resources error while using micropip

### ISSUE THREAD

**Issue by kofalt** [pyodide/pyodide#1611] opened 2021-05-26 18:17 UTC
When loading `pydicom` with micropip, the install call appears to succeed, but an exception occurs while importing.

Here's a trivial way to reproduce:

```html
<!DOCTYPE html>
<html>
<head>
<script src="https://cdn.jsdelivr.net/pyodide/v0.17.0/full/pyodide.js"></script>
</head>
<body>
Check browser console for output.
<script type="text/javascript">

async function main(){

await loadPyodide({
	indexURL : "https://cdn.jsdelivr.net/pyodide/v0.17.0/full/"
});

console.log(pyodide.runPython(`
	import sys
	sys.version
`));

await pyodide.runPythonAsync(`
	import micropip

	await micropip.install('pydicom')

	import pydicom
	print('Pydicom package imported.')
`);
}
main();

</script>
</body>
</html>
```

The full stack trace:

```
Uncaught (in promise) PythonError: Traceback (most recent call last):
  File "/lib/python3.8/asyncio/futures.py", line 178, in result
    raise self._exception
  File "/lib/python3.8/asyncio/tasks.py", line 280, in __step
    result = coro.send(None)
  File "/lib/python3.8/site-packages/pyodide/_base.py", line 419, in eval_code_async
    return await CodeRunner(
  File "/lib/python3.8/site-packages/pyodide/_base.py", line 272, in run_async
    await coro
  File "<exec>", line 6, in <module>
  File "/lib/python3.8/site-packages/pydicom/__init__.py", line 32, in <module>
    from pydicom.dataelem import DataElement
  File "/lib/python3.8/site-packages/pydicom/dataelem.py", line 18, in <module>
    from pydicom import config  # don't import datetime_conversion directly
  File "/lib/python3.8/site-packages/pydicom/config.py", line 192, in <module>
    import pydicom.overlays.numpy_handler as overlay_np  # noqa
  File "/lib/python3.8/site-packages/pydicom/overlays/__init__.py", line 1, in <module>
    from pydicom.overlays.numpy_handler import get_overlay_array
  File "/lib/python3.8/site-packages/pydicom/overlays/numpy_handler.py", line 40, in <module>
    from pydicom.pixel_data_handlers.numpy_handler import unpack_bits
  File "/lib/python3.8/site-packages/pydicom/pixel_data_handlers/__init__.py", line 2, in <module>
    from pydicom.pixel_data_handlers.util import (
  File "/lib/python3.8/site-packages/pydicom/pixel_data_handlers/util.py", line 15, in <module>
    from pydicom.data import get_palette_files
  File "/lib/python3.8/site-packages/pydicom/data/__init__.py", line 4, in <module>
    from .data_manager import (
  File "/lib/python3.8/site-packages/pydicom/data/data_manager.py", line 52, in <module>
    from pkg_resources import iter_entry_points
ModuleNotFoundError: No module named 'pkg_resources'
```

I also built locally via the `docker.io/pyodide/pyodide-env:16` image and the `0.17.0` repo tag:

```bash
# Launch container from repository's top folder
podman run --name pydev -it --rm -v "$PWD:/src" --shm-size 2g docker.io/pyodide/pyodide-env:16 /bin/bash

# Inside the container...

# Full build
time nice make

# The first time building, a KeyError exception was thrown:
#
# Thread 4 building pandas
# Thread 1 building imageio
# Error building pandas. Printing build logs.
# patching file pandas/_libs/src/ujson/python/ujson.c
# Traceback (most recent call last):
#   File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 360, in get_provider
#     module = sys.modules[moduleOrReq]
# KeyError: 'numpy'

# Just running the build again appeared to succeed this time, not sure why
time nice make

# Generates yml file for pydicom package
time python -m pyodide_build mkpkg pydicom

# Build pydicom
PYODIDE_PACKAGES="pydicom" make

# Convert resulting egg file to a wheel
cp packages/pydicom/build/pydicom-2.1.2/dist/pydicom-2.1.2-py3.8.egg /tmp
cd /tmp
wheel convert ./pydicom-2.1.2-py3.8.egg
```

However, this wheel file produced the same error.

**Comment by rth** [comment] 2021-05-26 19:37
The issue is that pydicom doesn't correctly specify dependencies. `pkg_resources` is part of `setuptools` however `setup.py` indicates that there are no dependencies. So a workaround for Pyodide is to load `setuptools` manually before loading `pydicom`.

It would be good to open an issue upstream about it. `setuptools` is often assumed to be installed by default, but that assumption doesn't hold for Pyodide. I'm going to close the issue but don't hesitate to comment if you still encounter difficulties with it.

**Closed by rth** 2021-05-26 19:37 UTC
