### ISSUE TITLE
Should I be getting a CORS error when installing "autosklearn" with micropip?

### ISSUE THREAD

**Issue by leonaburime** [pyodide/pyodide#2626] opened 2022-05-27 04:31 UTC
## 🐛 Bug

Not sure if Im doing anything wrong as this should be straight forward but trying to install "autosklearn" and getting a CORS error

### To Reproduce

`pyodide = await loadPyodide({ indexURL: 'https://cdn.jsdelivr.net/pyodide/v0.18.1/full/', }); await pyodide.loadPackage(['scikit-learn', 'micropip']);`

The package is imported like so
`pyodide.runPython(
import micropip
micropip.install('autosklearn')
import autosklearn.classification
, );`

### Expected behavior
I should be able to load any package - specifically "autosklearn" here

### Environment

- Pyodide Version: v0.18.1
- Browser version: Chrome Version 101.0.4951.64
- Any other relevant information:
Here is the error 
![170627722-c512d069-f19d-45ee-a452-2bb023132881](https://user-images.githubusercontent.com/8000641/170629188-3411b604-9dc9-424c-b772-2d32977fc85f.png)

**Comment by eagleoflqj** [comment] 2022-05-27 20:17
It's expected because there is no package called "autosklearn" on PyPI https://pypi.org/search/?q=autosklearn.
Nor am I able to install it locally using `pip install autosklearn`.

**Comment by leonaburime** [comment] 2022-05-27 20:22
@eagleoflqj  Try `pip install auto-sklearn`. I tried both and neither works.
Heres the package on PyPI - https://pypi.org/project/auto-sklearn/

**Comment by eagleoflqj** [comment] 2022-05-27 20:48
Then it becomes a new package request, as only pure python packages can be automatically installed.

**Comment by leonaburime** [comment] 2022-05-27 23:49
So if I wanted to contribute to this project and port it over so pyodide can load it...

1. A pure python Package is one exclusive written with Python right? [Since only 0.4% of autosklearn](https://github.com/automl/auto-sklearn) is not Python it wouldn't be hard to port over correct?
2. Why would this affect CORS?

**Comment by amitsaha** [comment] 2022-05-29 03:46
@leonaburime Regarding the CORS issue, how are your running your script? It seems like you are serving it from a local server? Could you please update with *exact* reproducing instructions for the bug?

**Comment by leonaburime** [comment] 2022-05-29 04:25
@amitsaha Correct. I downloaded the umijs frontend package but not sure how that affects it...


My `npm start` runs `cross-env UMI_ENV=dev umi dev` command

and this is the code that causes it

`async function main() {
    pyodide = await loadPyodide({
       indexURL: 'https://cdn.jsdelivr.net/pyodide/v0.18.1/full/',
     });
  await pyodide.loadPackage(['scikit-learn', 'micropip']);
  pyodide.runPython(
    '
      import micropip 
      micropip.install('autosklearn')
    ',
  );
  return pyodide;
}
pyodide = main();
`
- The single quotes are backticks 
- Im unsure as to why the spacing is so messed up

**Comment by hoodmane** [comment] 2022-05-29 04:33
The CORs problem is that there is no package on pypi called autosklearn. It's called `auto-sklearn`. The reason you get a CORS error is that pypi doesn't set CORS on the 404 page:
Fetching `https://pypi.org/pypi/auto-sklearn/json` returns a json response with cors set
Fetching `https://pypi.org/pypi/autosklearn/json` returns an http 404 page with no cors

On the main branch I believe we have fixed this: if on the development console:
https://pyodide-cdn2.iodide.io/dev/full/console.html

you run
```py
import micropip
await micropip.install("autosklearn")
```
it will say:
`ValueError: Can't fetch metadata for 'autosklearn' from PyPI. Please make sure you have entered a correct package name.`
If you spell auto-sklearn correctly
```py
import micropip
await micropip.install("auto-sklearn")
```
it will say:
```
ValueError: Can't find a pure Python 3 wheel for 'auto-sklearn'.
See: https://pyodide.org/en/stable/usage/faq.html#micropip-can-t-find-a-pure-python-wheel
You can use `micropip.install(..., keep_going=True)`to get a list of all packages with missing wheels.
```

Thanks to @ryanking13 for his work on improving the micropip error messages!

**Comment by leonaburime** [comment] 2022-05-29 04:54
@hoodmane Thanks so much for the comprehensive answer.  So this means that I need a package request for `auto-sklearn` correct? How hard is that process if I want to contribute?

**Comment by hoodmane** [comment] 2022-05-29 05:45
I tried this out and the automatically generated recipe file build successfully so it might be a simple case. Try following the directions here:
https://pyodide.org/en/stable/development/new-packages.html

**Comment by rth** [comment] 2022-05-29 08:44
Thanks to everyone who participated in the discussion! 

Closing as resolved, since I see there is now https://github.com/pyodide/pyodide/issues/2636 about building this package. So let's continue the discussion there.

**Closed by rth** 2022-05-29 08:44 UTC
Labels: bug
