### ISSUE TITLE
pyodide does not have requests package

### ISSUE THREAD

**Issue by DavoodFadaee** [pyodide/pyodide#3158] opened 2022-09-28 10:55 UTC
Hi,
 The pyodide does not have requests module.
is it possible to add it?

Thank you.

**Comment by ryanking13** [comment] 2022-09-29 01:40
Supporting requests requires Synchronous IO, which is not easy task (See: https://github.com/pyodide/pyodide/issues/1503) for now.

Closing as a duplicate of #398. Don't hesitate to comment there is you have ideas to share.

**Closed by ryanking13** 2022-09-29 01:40 UTC

**Comment by rth** [comment] 2022-09-29 07:19
You can currently use https://github.com/koenvo/pyodide-http for requests.
