### ISSUE TITLE
Reflect.construct not producing expected results

### ISSUE THREAD

**Issue by WebReflection** [pyodide/pyodide#3914] opened 2023-06-07 19:37 UTC
### To Reproduce

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Pyodide Reflect</title>
  <script>
    // expected: 0, 1, 2, 3
    console.log('JS Reflect.construct(Promise, Array(trap))');

    console.log(0);
    const p = Reflect.construct(Promise, Array((res, rej) => {
      console.log(1);
      res(3);
    }));
    console.log(2);
    p.then(console.log)
  </script>
  <script type="module">
    import {loadPyodide} from 'https://cdn.jsdelivr.net/pyodide/v0.23.2/full/pyodide.mjs';
    const runtime = await loadPyodide();
    // expected: 0, 1, 2, 3
    runtime.runPython(`
      from js import Array, Promise

      print('pyodide Promise.new(trap)')

      def trap(res, rej):
        print(1)
        res(3)

      print(0)
      p = Promise.new(trap)
      print(2)
      p.then(print)

    `);

    setTimeout(() => {
      // shenanigan: 0, 2 ...
      runtime.runPython(`
        from js import Array, Promise, Reflect

        print('pyodide Reflect.construct(Promise, Array(trap))')

        def trap(res, rej):
          print(1)
          res(3)

        print(0)
        p = Reflect.construct(Promise, Array(trap))
        print(2)
        p.then(print)

      `);
    }, 1000);
  </script>
</head>
</html>
```

### Expected behavior

0, 1, 2, 3

### Additional context

There's something not quite right in the way `Reflect.construct` addresses returned instances + it doesn't really construct as indeed the promise callback `trap` is never invoked.

**Comment by WebReflection** [comment] 2023-06-08 15:50
P.S. in an ideal world I'd love to also be able to write `Reflect.construct(Promise, [callback])` and use that list as transparent way to signal a well known JS array ... but I guess that's rather a feature request or a "nice to have" thing ... non-usable Reflect in a JS way is definitively a bigger issue.

**Comment by hoodmane** [comment] 2023-06-08 17:39
If you use the following:
```py
from pyodide.ffi import create_once_callable
p = Reflect.construct(Promise, Array(create_once_callable(trap)))
```
it works as expected. It also works fine to use:
```py
Promise.new(trap)
```
or
```py
from pyodide.ffi import create_once_callable
p = Reflect.construct(Promise, [trap])
```

If you `await` the promise in your original example, you get a clearer (but still slightly confusing) error message:
```js
pyodide.runPythonAsync(`
        from js import Array, Promise, Reflect
        def trap(res, rej):
          print(1)
          res(3)

        print(0)
        p = Reflect.construct(Promise, Array(trap))
        print(2)
        await p.then(print)
`);
```

```py
pyodide.ffi.JsException: Error: This borrowed proxy was automatically destroyed at the end of a function call. Try using create_proxy or create_once_callable.
The object was of type "function" and had repr "<function trap at 0x1027288>"
```
from this error, you might figure out that the issue is resource management around the `Array(trap)` call, but it is a bit obscure. I think it might help to add the name of the function that was called to the error context.

> in an ideal world I'd love to also be able to write `Reflect.construct(Promise, [callback])` and use that list as transparent way to signal a well known JS array

Can you explain what you mean by this? I do not understand.

**Comment by hoodmane** [comment] 2023-06-08 17:49
Ah so
```py
p = Reflect.construct(Promise, [trap])
```
fails in v0.23.2 but the failure is fixed on the main branch probably due to changes made to resolve some of your other bug reports @WebReflection.

**Comment by hoodmane** [comment] 2023-06-08 17:53
In particular, it works to pass a python list since #3853 was merged.

**Comment by WebReflection** [comment] 2023-06-08 18:02
btw, my `Array(trap)` was after the fact I am not sure I should bring ffi in to make it work (other runtimes don't need it) but I am OK with this resolved as won't fix, specially knowing `Reflect.construct(Promise, [fn])` works ... I wonder why the latter is straight forward but the former isn't though, but then again none of these are blockers to me, just a documentation matter.

**Comment by hoodmane** [comment] 2023-06-08 21:49
> I am not sure I should bring ffi in to make it work (other runtimes don't need it) 

Well if you want code that is runtime agnostic, you could manage this with:
```py
try:
   from pyodide.ffi import create_once_callable
else:
   create_once_callable = lambda x: x

# ... code using create_once_callable
```

**Comment by hoodmane** [comment] 2023-06-08 21:52
Since you asked, I can write a long explanation about why it works this way. I think this is the "best possible" design, but it is more designed around the constraint of making it possible and ergonomic to use Pyodide in cases things where memory management matters at the cost of making it slightly less ergonomic in the case where it doesn't matter.

Please let me know if you have questions or opinions!

The issue is about garbage collection and resource management. Basically, the trouble is that to convert a Python object to a JavaScript `PyProxy` object, the JavaScript `PyProxy` object owns a reference to the Python object and keeps it alive. If you leak the `PyProxy`, then you have to wait until the v8 `FinalizationRegistry` decides to run the finalizer. In practice, this often takes a long time. Furthermore, there is no way to advice v8 about how much memory is actually owned by a proxy. 

For instance, imagine that the object owns a slice of the wasm heap. We can imagine the following code:
```js
const finalizationRegistry = new FinalizationRegistry(ptr => {
   // Release memory from heap
   Module._free(ptr);
});
const size = 100000;
const ptr = Module._malloc(size);
const o = {
   ptr,
   size,
   // Fancy methods to do stuff with the ptr
}
// No way to inform finalizationRegistry that ptr owns 100,000 bytes of 
// memory and would be useful to free soon, browser garbage collector
// only sees that it has two Number fields.
finalizationRegistry.register(o, ptr, o);
```
There's no way around this when calling into Python, but if we are calling out from Python into JavaScript then we can create the object that owns the memory before the function call and automatically release it when the function call is done.  A slightly contrived example:
```js
function lookupKey(obj, key) {
   return obj.get(key);
}
pyodide.runPython(`
   from js import lookupKey
   huge_dictionary = {"some_key": 7 } # imagine a lot of other stuff in this!
   # works as expected, doesn't leak the dictionary
   val = lookupKey(huge_dictionary, "some_key")
`);
```

Most functions don't store references to their arguments, so all of these existing js functions work without change and don't cause any memory leaks even when called with huge Python objects. When the function **does** store the Python object, it causes an error but the error message can tell you useful context about the problem:
```js
let dict;
function setDictionary(d) {
   dict = d;
}
function lookupKey(key) {
   return dict.get(key);
}
pyodide.runPython(`
   from js import setDictionary, lookupKey
   huge_dictionary = {"some_key": 7 } # imagine a lot of other stuff in this!
   # still doesn't leak the dictionary, but it doesn't work
   setDictionary(huge_dictionary)
   lookupKey("some_key")
`);
```
the error says:
```
This borrowed proxy was automatically destroyed at the end of a function call. Try using create_proxy or create_once_callable.
The object was of type "dict" and had repr "{'some_key': 7}"
```
And then you have to either modify the js code:
```js
let dict;
function setDictionary(d) {
   if(dict) {
      dict.destroy();
   }
   if (d) {
      d = d.copy();
   }
   dict = d;
}
function lookupKey(key) {
   return dict.get(key);
}
pyodide.runPython(`
   from js import setDictionary, lookupKey
   huge_dictionary = {"some_key": 7 } # imagine a lot of other stuff in this!
   setDictionary(huge_dictionary)
   assert lookupKey("some_key") == 7
   setDictionary(None) # dictionary is freed now
`);
```
Or you can modify the Python code:
```
This borrowed proxy was automatically destroyed at the end of a function call. Try using create_proxy or create_once_callable.
The object was of type "dict" and had repr "{'some_key': 7}"
```
And then you have to either modify the js code:
```js
function setDictionary(d) {
   dict = d;
}
function lookupKey(key) {
   return dict.get(key);
}
pyodide.runPython(`
   from js import setDictionary, lookupKey
   from pyodide.ffi import create_proxy
   proxy = None
   def set_dictionary(d):
      global proxy
      if proxy:
         proxy.destroy()
      if d is not None:
         proxy = create_proxy(d)
      else:
         proxy = None
      setDictionary(proxy)

   huge_dictionary = {"some_key": 7 } # imagine a lot of other stuff in this!
   setDictionary(huge_dictionary)
   assert lookupKey("some_key") == 7
   setDictionary(None) # dictionary is freed now
`);
```
or of course if you just want to leak the Python objects and let `FinalizationRegistry` eventually do its work you can use `create_proxy`. I haven't figured out a good way to support both the people who are doing more memory sensitive things and the people who want everything to work as easily as possible and don't care about leaking things.

A useful exception to this is that if the function returns a promise (respectively a generator), then the arguments are kept alive until the promise is resolved (resp. the generator is exhausted). This means that an async function works as expected:
```js
async function doSomething(pyobj) {
	pyobj.use_it();
    await something();
    // pyobj is still alive because Pyodide waits for the promise to be resolved to reclaim it
	pyobj.use_it();    
}
```
Of course this means that the following will leak:
```js
function leakArsg(pyobj) {
    // Return a promise that will never resolve
	return new Promise((res, rej) => {}); 
}
```

**Closed** 2023-10-24 23:13 UTC
Labels: bug
