### ISSUE TITLE
Interrupt checking has become less reliable in 0.20.0

### ISSUE THREAD

**Issue by alexmojaki** [pyodide/pyodide#2400] opened 2022-04-17 21:36 UTC
## 🐛 Bug

`setInterruptBuffer` *generally* works but some kinds of Python code no longer get interrupted in 0.20.0.

### To Reproduce

In 0.19.1, this Python code could be interrupted and a KeyboardInterrupt would be raised:

```python
while True:
    pass
```

In 0.20.0, that code no longer gets interrupted and just runs forever. This code *does* get interrupted:

```python
while True:
    str(3)
```

An example of more 'realistic' code that doesn't get interrupted:

```python
for i in range(100000000):
    i *= 2
    i += 9 + int(i < 3)
    str()
```

Here is where I'm actually testing this:

https://github.com/alexmojaki/pyodide-worker-runner/blob/5d7a7ba4652e23fb1f0483876793c3756cd688ef/test/index.ts#L197-L213

Upgrading that package to use 0.20.0 broke that test, replacing `pass` with `str(3)` as above fixed it (https://github.com/alexmojaki/pyodide-worker-runner/pull/9/commits/aee33fbead9c9afd22c3facc7c37226cb4138cc2)

### Expected behavior

Any pure-python synchronous code should eventually be interrupted, even something contrived like `while True: pass`, because sometimes people intentionally try stupid things to test what will happen, and sometimes people make dumb mistakes.

### Environment

- Pyodide Version: 0.20.0
- Browser version: 6 combinations of Chrome, Firefox, and Edge on Windows, OSX, and Ubuntu between myself and Browserstack.

**Comment by alexmojaki** [comment] 2022-04-17 21:39
Guessing somewhat blindly here, could https://github.com/pyodide/pyodide/pull/2332 be related?

**Comment by hoodmane** [comment] 2022-04-17 22:05
I think this problem was introduced in the update to python 3.10, I remember changing the interrupt handling test to work around this problem so we can probably track it down with git blame on the tests. In Python 3.10 they significantly restructured `ceval.c` and I think the difficulty is related to that -- if certain opcodes pass through the interrupt check but others don't then a loop would be interruptible only if the body contains an opcode that triggers the check. I think this is consistent with the symptoms.

**Comment by hoodmane** [comment] 2022-04-18 00:18
#2332 was merged between v0.20.0a1 and v0.20.0, can you try the test on v0.20.0a1 too? That would help us decide whether the problem was caused in #2332 or #2225. I suspect it is still around in v0.20.0a1 and that it is a regression in #2225.

**Comment by hoodmane** [comment] 2022-04-18 00:29
See:
[`f06a332` (#2225)](https://github.com/pyodide/pyodide/pull/2225/commits/f06a33271e749d2daba4fe0f8142f9196d59d74f)

**Comment by hoodmane** [comment] 2022-04-18 01:44
Yeah so I injected this into the interrupt checker code to log which opcodes get checked:
```js
const ts = Module.__PyThreadState_UncheckedGet();
const frame = Module._PyThreadState_GetFrame(ts);
const lasti = HEAP32[frame/4+13];
const co_bytes = HEAP32[HEAP32[frame/4+4]/4 + 9];
const co_str = _PyBytes_AsString(co_bytes);
if(lasti === -1){
   console.log("1st of frame");
} else {
   console.log("last instruction", HEAPU8[co_str + 2*lasti]);
}
Module._Py_DecRef(frame);
```
I only see 86 (YIELD_VALUE) 131, 141, 142 and 161 (various method call opcodes) though I haven't run that much code with this enabled yet so probably there are other opcodes that will turn up.

But the code block
```js
for i in range(100000000):
    i *= 2
    i += 9 + int(i < 3)
    str()
```
has two `CALL_FUNCTION` opcodes in it, not sure why it never does the check.

**Comment by hoodmane** [comment] 2022-04-18 02:10
Running the same test in Python v3.9, I see interrupt checks at opcodes `ROT_FOUR`, `INPLACE_MULTIPLY`, `INPLACE_ADD`, `LOAD_NAME`, and `LOAD_CONST`. So I think that confirms that the problem is with the `ceval.c` patch since I ported it to v3.10.2. Since they've upstreamed this patch, I guess I should report this in the cpython repo too...

**Comment by hoodmane** [comment] 2022-04-18 04:27
Ah we need to update `CHECK_EVAL_BREAKER` to also call `_Py_CheckEmscriptenSignalsPeriodically`.

**Comment by hoodmane** [comment] 2022-04-18 04:29
It seems that I included this check in the upstream cpython patch but backported the patch incorrectly.

**Closed** 2022-04-19 12:40 UTC
Labels: bug
