### ISSUE TITLE
add pyarrow package

### ISSUE THREAD

**Issue by ivandorte** [pyodide/pyodide#3171] opened 2022-10-05 19:32 UTC
## 🐍 Package Request

- Package Name and Version : pyarrow / latest
- Package URL : https://pypi.org/project/pyarrow/
- Package Dependencies that needs to be resolved first: Not sure

**Comment by ryanking13** [comment] 2022-10-06 00:22
Closing as a duplicate of #2933, don't hesitate to comment there.

**Closed by ryanking13** 2022-10-06 00:22 UTC
Labels: new package request
