### ISSUE TITLE
Doesn't work in Opera on iOS 15.4.1 (SyntaxError)

### ISSUE THREAD

**Issue by ivanistheone** [pyodide/pyodide#2540] opened 2022-05-10 14:23 UTC
## 🐛 Bug

I tried the [pyodide repl](https://pyodide.org/en/stable/console.html) running `from sympy import cot` and got a traceback:
![IMG_1303](https://user-images.githubusercontent.com/163966/167442842-47c0868c-0e2d-4c67-b779-c19e45d639b6.PNG)

I did a separate test `from sympy import solve` and that works fine. So it seems to be some specific code paths that are not Opera-compatible.
 

I also tried the [pyodide repl](https://pyodide.org/en/stable/console.html) again using Opera on iOS and it (from sympy import *) seems to hang (no errors are displayed, and I don't know how to check console on mobile).

### To Reproduce

1. Go to [pyodide repl](https://pyodide.org/en/stable/console.html) 
2.  enter `from sympy import cot`

### Expected behavior

No errors.

### Context

I'm running iOS 15.4.1 on a iPhone SE 2nd gen.

**Comment by rth** [comment] 2022-05-10 15:16
I can't test it in Opera on this IPhone (Browserstack doesn't ship Opera), but I can confirm that at least on MacOS Monterey and Opera 86 this import works.

So I think similarly to #2539 It's a resource issue (little RAM) on iPhone SE 2nd gen.
Also Opera Mobile is not a browser we [officially support](https://pyodide.org/en/stable/usage/index.html#supported-browsers). It's based on Chromium so it should work in practice, but it still might be better in general to use a more mainstream browser on mobile. Not that it would help in this situation.

**Comment by eagleoflqj** [comment] 2022-05-11 01:38
Any browser on iOS has to use Webkit as its engine. So the Opera here can't be Chromium based. That makes me more convinced it's a Webkit bug.

**Comment by rth** [comment] 2022-05-11 15:18
> Any browser on iOS has to use Webkit as its engine. So the Opera here can't be Chromium based.

Are you sure about that? I don't have an iPhone, but as far as I understand one can install Chrome on iOS https://apps.apple.com/us/app/google-chrome/id535886823  Also I was checking the wiki page for [Opera Mobile](https://en.wikipedia.org/wiki/Opera_Mobile) it says they switched from WebKit to Chromium in 2013, and there is no mention of it not being a case on iOS. Having a browser with different engines depending on the OS would be extremely cost-ineffective to develop.

Though I'm certainly open to the possibility that https://github.com/pyodide/pyodide/issues/2539 is a WebKit bug.

**Comment by rth** [comment] 2022-05-11 18:58
OK, I'm closing in favor of https://github.com/pyodide/pyodide/issues/2539 since it appears that all browsers use Webkit on IOS, so there is no point to have multiple issues about it.

**Closed by rth** 2022-05-11 18:58 UTC
Labels: bug
