### ISSUE TITLE
Matplotlib `plt.subplots()` not working

### ISSUE THREAD

**Issue by aidam38** [pyodide/pyodide#1313] opened 2021-03-10 08:40 UTC
![image](https://user-images.githubusercontent.com/26225771/110599486-354efd00-8183-11eb-8192-cdf20f774296.png)

**Problem:** Running the following code

```
import matplotlib.pyplot as plt
fig, ax = plt.subplots()
```

throws the following error (with the newest version compiled locally)

```
Traceback (most recent call last):
  File "<exec>", line 12, in run_code
  File "<string>", line 3, in <module>
  File "/lib/python3.8/site-packages/matplotlib/cbook/deprecation.py", line 451, in wrapper
    return func(*args, **kwargs)
  File "/lib/python3.8/site-packages/matplotlib/pyplot.py", line 1288, in subplots
    axs = fig.subplots(nrows=nrows, ncols=ncols, sharex=sharex, sharey=sharey,
  File "/lib/python3.8/site-packages/matplotlib/cbook/deprecation.py", line 451, in wrapper
    return func(*args, **kwargs)
  File "/lib/python3.8/site-packages/matplotlib/figure.py", line 1522, in subplots
    return (self.add_gridspec(nrows, ncols, figure=self, **gridspec_kw)
  File "/lib/python3.8/site-packages/matplotlib/gridspec.py", line 336, in subplots
    axarr[row, col] = figure.add_subplot(
  File "/lib/python3.8/site-packages/matplotlib/figure.py", line 1404, in add_subplot
    return self._add_axes_internal(key, ax)
  File "/lib/python3.8/site-packages/matplotlib/figure.py", line 1411, in _add_axes_internal
    self.stale = True
  File "/lib/python3.8/site-packages/matplotlib/artist.py", line 224, in stale
    self.stale_callback(self, val)
  File "/lib/python3.8/site-packages/matplotlib/pyplot.py", line 733, in _auto_draw_if_interactive
    fig.canvas.draw_idle()
  File "/lib/python3.8/site-packages/matplotlib/backends/wasm_backend.py", line 234, in draw_idle
    window.setTimeout(self.draw, 1)
JsException: PythonError: AttributeError: 'method' object has no attribute 'prototype'
```

With the version 0.16.1, it instead throws an error to the JS console saying something similar
```
pyodide.asm.js:8 Uncaught (in promise) Error: TypeError: set expected at most 1 arguments, got 2

    at _hiwire_throw_error (pyodide.asm.js:8)
    at _pythonexc2js (pyodide-cdn2.iodide.io/v0.15.0/full/pyodide.asm.wasm:wasm-function[358]:0xfc9e1)
    at __pyproxy_apply (pyodide-cdn2.iodide.io/v0.15.0/full/pyodide.asm.wasm:wasm-function[356]:0xfc311)
    at Module.__pyproxy_apply (pyodide.asm.js:8)
    at Object.apply (pyodide.asm.js:8)
    at pyroam.js:497
    at step (pyroam.js:420)
    at Object.next (pyroam.js:350)
    at pyroam.js:322
    at new Promise (<anonymous>)
    at __awaiter (pyroam.js:301)
    at Object.runPython (pyroam.js:489)
    at pyroam.js:1107
    at step (pyroam.js:1012)
    at Object.next (pyroam.js:942)
    at pyroam.js:914
    at new Promise (<anonymous>)
    at __awaiter (pyroam.js:893)
    at Object.runActiveBlockAndWriteToNext (pyroam.js:1098)
    at pyroam.js:1312
    at step (pyroam.js:1284)
    at Object.next (pyroam.js:1214)
    at pyroam.js:1186
    at new Promise (<anonymous>)
    at __awaiter (pyroam.js:1165)
    at HTMLDocument.handleKeyPress (pyroam.js:1309)
    at HTMLDocument.sentryWrapped (bundle.min.js:2)
_hiwire_throw_error @ pyodide.asm.js:8
_pythonexc2js @ pyodide.asm.wasm:0xfc9e1
__pyproxy_apply @ pyodide.asm.wasm:0xfc311
Module.__pyproxy_apply @ pyodide.asm.js:8
```

Running 
```
import matplotlib.pyplot as plt
plt.plot(...)
```
directly works instead.

Tested in multiple browsers and both `runPython` and `runPythonAsync`. 

Here's the code of the project (Python notebooks in Roam Research): https://github.com/aidam38/pyroam.

**Comment by rth** [comment] 2021-03-10 19:43
Thanks for the report. So far I can't reproduce in the dev console https://pyodide-cdn2.iodide.io/dev/full/console.html (that corresponds to the latest build of master)

**Comment by rth** [comment] 2022-09-17 07:43
Closing as non-reproducible and this was with a Pyodide  version from some time ago. If you still encounter this issue please comment.

**Closed by rth** 2022-09-17 07:43 UTC
