### ISSUE TITLE
Unexpected disappearing created elements

### ISSUE THREAD

**Issue by goatchurchprime** [pyodide/pyodide#389] opened 2019-04-20 12:13 UTC
When I run this code I get a button that then disappears after an undefined number of seconds:

```
from js import iodide
b1 = iodide.output.element('button')
b1.textContent = "Not Gone Yet!"
b1 = 0
```

I think it's because the Python object that made the button has been programmed to remove it from the document when it gets garbage collected.  

This is not how it works in Javascript where, when you create and then insert something into the document, it stays there until you call the remove() function on it.  (It came as quite unexpected behavior when I first made a loop to generate an array of buttons.)

I am not totally sure what's going on; sometimes buttons can disappear even when I still have a reference to the object (although in a different variable), so even if this is the intended behavior, it's not working perfectly.  

I think this issue (that your document objects may disappear with your python objects) needs flagging up in the demo notebook, and possibly a lot of thought as to whether this is potentially a pitfall.

**Comment by mdboom** [comment] 2019-04-25 12:32
Hmm...  Strangely I can't reproduce.

The line `b1 = 0` will destroy the *Python* reference to the object, but won't destroy the Javascript object by virtue of it being inserted in the DOM and thus safe from garbage collection.

It does, however, disappear when the cell containing the Python code is edited.  I think this is by design so the cell can be rerun without creating additional output elements.  But it would be good to get some context from @bcolloran or @hamilton on this.

**Comment by bcolloran** [comment] 2019-04-25 17:29
that's correct @mdboom -- there are two cases that we need to be able to handle:
1) as you say, if you rerun a chunk, we need to update the DOM with out continually adding more and more elements
2) if you go in and delete `b1 = iodide.output.element('button')`, we need to be able to remove it from the DOM

the simplest way to do this (without getting into complicated DOM diffing) was to just invalidate any programmatically generated DOM associated with a chunk as soon a chunk is edited.

**Comment by hoodmane** [comment] 2021-01-01 21:39
@rth @dalcde  Can we close this since we no longer support iodide?

**Closed** 2021-08-02 14:25 UTC
