### ISSUE TITLE
Cannot read property 'apply' of undefined error in scikit-learn

### ISSUE THREAD

**Issue by Sm4ster** [pyodide/pyodide#492] opened 2019-07-20 22:16 UTC
Hello everyone,

I have been experimenting with Pyodide and was trying to execute some scikit-learn code.
I took the code directly from the [documentation of scikit-learn](https://scikit-learn.org/stable/modules/generated/sklearn.decomposition.FactorAnalysis.html)

This is the snippet in question:
```
from sklearn.datasets import load_digits
from sklearn.decomposition import FactorAnalysis
X, _ = load_digits(return_X_y=True)
transformer = FactorAnalysis(n_components=7, random_state=0)
X_transformed = transformer.fit_transform(X)
```

However, after the last line of code it throws the following error:
```
**pyodide.asm.js:formatted:444 Uncaught (in promise) TypeError: Cannot read property 'apply' of undefined**
    at env.<computed> (pyodide.asm.js:formatted:444)
    at byn$fpcast-emu$_dlu_c_ (wasm-function[2122]:34)
    at _f2py_rout__flinalg_dlu_c (wasm-function[139]:984)
    at byn$fpcast-emu$_f2py_rout__flinalg_dlu_c (wasm-function[2123]:13)
    at _fortran_call (wasm-function[148]:253)
    at byn$fpcast-emu$_fortran_call (wasm-function[2134]:10)
    at wasm-function[837]:1420
    at wasm-function[2749]:1110
    at wasm-function[2744]:44570
    at wasm-function[20461]:7
```
I have no idea what to make of it, but maybe someone else has?
Thanks in advance :)

**Comment by rth** [comment] 2019-10-27 10:25
Thanks for the report. I can confirm. The issue is likely that lu decomposition in `scipy.linalg` does not work properly.

A workaround in this particular case is to use a different solver: `svd_method="lapack"` should work.

**Comment by dmikushin** [comment] 2020-06-19 18:29
I came across the same problem when using scipy.optimize:

```
#solve the optimisation
opt = optimize.minimize(func, init_x, bounds=bnds)
```

Any clue workaround for this one? Thanks in advance!

**Comment by rth** [comment] 2021-02-08 19:35
I believe this was fixed by https://github.com/iodide-project/pyodide/pull/1102 which will be included in the next release. The example in the original post now works fine. This also likely applies to the issue with scipy.optimize. Please comment if you you still experience issues.

**Comment by rth** [comment] 2021-04-07 16:02
No it looks like it's still and issue, e.g. with the LBFGS solver in https://github.com/pyodide/pyodide/issues/1440

**Comment by CKPOON0619** [comment] 2021-12-08 12:10
Trying to run statsmodels ARIMA and got similar error with L-BFGS solver. 
`Stack (most recent call first):
pyodide.asm.js:14   File "/lib/python3.9/site-packages/scipy/optimize/lbfgsb.py", line 319 in _minimize_lbfgsb
pyodide.asm.js:14   File "/lib/python3.9/site-packages/scipy/optimize/lbfgsb.py", line 192 in fmin_l_bfgs_b
pyodide.asm.js:14   File "/lib/python3.9/site-packages/statsmodels/tsa/arima_model.py", line 566 in _fit_start_params
pyodide.asm.js:14   File "/lib/python3.9/site-packages/statsmodels/tsa/arima_model.py", line 945 in fit
pyodide.asm.js:14   File "<exec>", line 42 in <module>
pyodide.asm.js:14   File "/lib/python3.9/site-packages/_pyodide/_base.py", line 345 in run_async
pyodide.asm.js:14   File "/lib/python3.9/site-packages/_pyodide/_base.py", line 494 in eval_code_async
pyodide.asm.js:14   File "/lib/python3.9/asyncio/tasks.py", line 256 in __step
pyodide.asm.js:14   File "/lib/python3.9/asyncio/events.py", line 80 in _run`

**Comment by rth** [comment] 2021-12-08 20:57
L-BFGS in scipy is in Fortran and likely something went wrong at the Python/Fortran interface there. It would be interesting to see how this would be impacted by #2019 since the original error is in the function pointers casts code.

Also related to https://github.com/pyodide/pyodide/issues/549

**Comment by hoodmane** [comment] 2022-01-01 16:07
I'm going to close this one because the code example here don't produce any error since v0.17.0. The error in #1440 does reproduce.

**Closed by hoodmane** 2022-01-01 16:07 UTC
Labels: bug, scipy, scikit-learn
