### ISSUE TITLE
CPython build does not use ccache

### ISSUE THREAD

**Issue by dalcde** [pyodide/pyodide#1007] opened 2021-01-02 01:34 UTC

**Comment by hoodmane** [comment] 2021-01-02 01:38
Does this mean that if you change the patches to CPython it takes as much time to rebuild as it did the first time?

**Comment by dalcde** [comment] 2021-01-02 01:51
I think that is one particular consequence, yes.

**Comment by dalcde** [comment] 2021-01-02 02:29
With newer emscripten versions, we can specify `EM_COMPILER_WRAPPER=ccache` and solve our ccache problems once and for all

**Comment by rth** [comment] 2021-02-07 12:03
We can probably start using `EM_COMPILER_WRAPPER` now and remove some of custom ccache setup we have.

**Comment by rth** [comment] 2021-07-16 22:36
Actually, this is an issue again now. Re-opening. I did a bisect and this issue starts happening on main after https://github.com/pyodide/pyodide/pull/1550 is merged. However I really can't see how that PR could have this impact, and I also can't reproduce this change locally before/after that commit. 

Before for the `build cpython` step we had,
```
cache hit (direct)                   732
cache hit (preprocessed)               0
cache miss                             2
cache hit rate                     99.73 %
```
now we have
```
cache hit (direct)                     0
cache hit (preprocessed)               0
cache miss                             0
cache hit rate                      0.00 %
```

I'm a bit out of ideas what could be causing this: Docker image is the same, we are not installing any system dependency, emsdk hash is the same, and Pyodide code is mostly the same. This only affects CPython build: compilation of emsdk and packages is still cached.


This is the main reason why build-core is slow now.

**Closed** 2021-09-11 12:22 UTC
