### ISSUE TITLE
Failed to run pyodide from downloaded release files

### ISSUE THREAD

**Issue by eyalk11** [pyodide/pyodide#1897] opened 2021-10-23 13:21 UTC
Hi,
I tried to run it by downloading the last release and extracting it, afterwards running `python -m http.server`.
chrome ver 95.0.4638.54 . python 3.9.6. 

It writes 
```
Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec.
console.html:151 
        
       Uncaught (in promise) TypeError: Failed to fetch dynamically imported module: http://localhost:8000/pyodide.asm.js
```

both in chrome and edge

**Comment by eyalk11** [comment] 2021-10-24 00:16
After building it , it indeed worked from build dir..

**Comment by rth** [comment] 2021-11-05 20:48
Was the issue solved then? Can we close this issue.

**Comment by eyalk11** [comment] 2021-11-06 15:02
The issue was resolved by building it.. 

I did not do anything else, so I don't see how it could have been resolved.

**Comment by rth** [comment] 2021-11-07 11:06
Right, sorry, I misread your post. 

What likely happens is that the installed python is older, and you need  Python 3.7.5+ as indicated the [docs](https://pyodide.org/en/stable/usage/downloading-and-deploying.html#serving-locally) so that the `http.server` would return correct MIME types.

Can you please re-try after making sure you are using  Python 3.7.5+ ? We should probably update the docs with a mention that it really doesn't work for previous python versions.

**Comment by eyalk11** [comment] 2021-12-06 23:02
Hi, I missed your comment. `python 3.9.6.` is written at the first message.

**Comment by ryanking13** [comment] 2024-06-29 08:39
Closing as no activity and I can't reproduce the error, but don't hesitate to comment more if you still experience the same issue.

**Closed by ryanking13** 2024-06-29 08:39 UTC
