### ISSUE TITLE
micropip import error

### ISSUE THREAD

**Issue by eyalk11** [pyodide/pyodide#1899] opened 2021-10-24 00:35 UTC
After building pyodide, I tried the following code : 
```
            pyodide.loadPackage("micropip").then(() => {
                pyodide.runPythonAsync(`
                    import micropip
                `);
            });
```
```
pyodide.asm.js:14 Uncaught (in promise) PythonError: Traceback (most recent call last):
  File "/lib/python3.9/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/lib/python3.9/asyncio/tasks.py", line 256, in __step
    result = coro.send(None)
  File "/lib/python3.9/site-packages/_pyodide/_base.py", line 494, in eval_code_async
    await CodeRunner(
  File "/lib/python3.9/site-packages/_pyodide/_base.py", line 345, in run_async
    coroutine = eval(self.code, globals, locals)
  File "<exec>", line 2, in <module>
ModuleNotFoundError: No module named 'micropip'

    at new_error (pyodide.asm.js:14)
    at pyodide.asm.wasm:0x1b9399
    at pyodide.asm.wasm:0x1bd7d6
    at pyodide.asm.wasm:0x853699
    at pyodide.asm.wasm:0x1f73c1
    at pyodide.asm.wasm:0x2f2f19
    at pyodide.asm.wasm:0x87250d
    at pyodide.asm.wasm:0x23ed39
    at pyodide.asm.wasm:0x8708c8
    at pyodide.asm.wasm:0x1f7b76
```

I built just some of packages, because of some errors. But `./packages/micropip/build/micropip-0.1/micropip` exists.

**Comment by ryanking13** [comment] 2021-11-01 12:37
It seems like multiple Python versions (Python 3.9 and Python 3.8) are installed in your system, and Python 3.8 is used when building Python packages instead of Python 3.9, which is a bug.

I think we can prevent this by strictly checking that `pyodide-build` is using the same Python version of what was used to build Pyodide.

https://github.com/pyodide/pyodide/blob/4042db26158c5c78cc8be6313927c29e5bba9181/pyodide-build/pyodide_build/__main__.py#L1

**Comment by ryanking13** [comment] 2021-11-06 11:57
I believe this issue is resolved with #1924.
@eyalk11 I would be very grateful if you could help us verify this.

**Comment by eyalk11** [comment] 2021-11-06 14:35
Hi, I tried this, and it didn't solve it.

**Comment by ryanking13** [comment] 2021-11-06 23:02
> Hi, I tried this, and it didn't solve it. My previous mitigation worked.

Hmm... I can't reproduce it.

Could you try 

```
rm -rf packages/build-logs/*.log && make clean && make
```

and show us the content of `packages/build-logs/micropip.log`?

**Comment by rth** [comment] 2022-09-17 08:03
Closing as resolved (if you  still experience this please comment)

**Closed by rth** 2022-09-17 08:03 UTC
Labels: bug, build
