### ISSUE TITLE
`OSError: [Errno 9] Bad file descriptor` when trying to load `.npy` files, works with `.npz` file format

### ISSUE THREAD

**Issue by agriyakhetarpal** [pyodide/pyodide#4541] opened 2024-02-22 14:41 UTC
## 🐛 Bug

NumPy is unable to load arrays from `.npy` binaries, but it can read from compressed `.npz` archives.

### To Reproduce

I noticed this error when compiling PyWavelets (`pywt`) from source via the Emscripten toolchain.

In an activated virtual environment created by Pyodide, run the following:

```bash
git clone https://github.com/PyWavelets/pywt.git
pip install .
```

and then

```python
import pywt
import numpy as np

aero = pywt.data.aero()

ref = np.array([[178, 178, 179],
                    [170, 173, 171],
                    [185, 174, 171]])

np.testing.assert_allclose(aero[:3, :3], ref)
```

should fail. However, [after converting](https://github.com/PyWavelets/pywt/pull/701/files#diff-86b5b5c7cbe8cc8368f6991c914b7263019507351ce567543cbf2b627b91aa57) these `.npy` files to `.npz`, NumPy can safely load the arrays from the files as requested.

Here is an example of conversion from `.npy` to `.npz`:

```python
import numpy as np
ecg = np.load("pywt/data/ecg.npy")
np.savez(file="ecg.npz", data=ecg)
```

after which `ecg.npz` can be loaded as follows:

```python
import numpy as np
loaded = np.load("ecg.npz")
print(loaded["data"])
```

### Expected behavior

The Pyodide environment should be able to load the `.npy` file format stored in a directory, but [fails with multiple `OSError`s](https://github.com/agriyakhetarpal/pywt/actions/runs/7993252511/job/21828629911), possibly due to the lack of a server for filesystem access as the Pyodide documentation mentions – but this doesn't explain why `.npz` files work?

The expected behaviour should be that all file formats work.

### Environment

- Pyodide Version: `pyodide-build` version 0.25.0
- Browser version:  N/A
- Any other relevant information:

### Additional context

xref: https://github.com/PyWavelets/pywt/pull/701

**Comment by hoodmane** [comment] 2024-02-22 15:56
Thanks for the report @agriyakhetarpal. So far I am not able to reproduce it. What is the traceback you are seeing?

I did the following steps:
```sh
mkdir tmp/pyodide-bug-4541
cd tmp/pyodide-bug-4541
python3.11 -m venv .venv
pip install pyodide-build
pyodide venv .venv-pyodide
git clone https://github.com/PyWavelets/pywt.git --depth 1
pyodide build pywt
.venv-pyodide/bin/pip install pywt/dist/*
```
Then I made a file with the contents you provided:
```py
import pywt
import numpy as np

aero = pywt.data.aero()

ref = np.array([[178, 178, 179],
                    [170, 173, 171],
                    [185, 174, 171]])

np.testing.assert_allclose(aero[:3, :3], ref)
```
Then I ran
```sh
.venv-pyodide/bin/python reproduction.py
```
and this executed the code without error.

**Comment by rgommers** [comment] 2024-02-22 16:27
> So far I am not able to reproduce it. What is the traceback you are seeing?

Ah, that may be a timing issue - I just merged the workaround (and a Pyodide CI job from @agriyakhetarpal!) at https://github.com/PyWavelets/pywt/pull/701.

With commit `e69b126c096` I think it'll reproduce.

**Comment by agriyakhetarpal** [comment] 2024-02-22 16:27
Thanks for verifying, you might have to go back one commit in the `pywt` directory and re-run the `reproduction.py` script, because we had fixed this upstream by converting the `.npy` files to `.npz` before your message here: https://github.com/PyWavelets/pywt/pull/701

Moreover, the above example – it turns out, used a `.npz` file, so that was probably invalid.

Maybe accessing the files can be tried directly instead of the API that `pywt` provides?

```python
import numpy as np
loaded_data = np.load("pywt/data/'ecg.npy')
```

and then running array operations on the `loaded_data` array (it should fail at the time of loading, ideally)?

**Comment by hoodmane** [comment] 2024-02-22 16:46
Okay, commit `e69b126c096` and
```py
import numpy as np

loaded_data = np.load("pywt/pywt/data/ecg.npy")
```
I now reproduce the bug:
```py
Traceback (most recent call last):
  File "/tmp/pyodide-bug-4541/repro.py", line 11, in <module>
  File "/tmp/pyodide-bug-4541/.venv-pyodide/lib/python3.11/site-packages/numpy/lib/npyio.py", line 422, in load
  File "/lib/python311.zip/contextlib.py", line 589, in __exit__
  File "/lib/python311.zip/contextlib.py", line 574, in __exit__
OSError: [Errno 8] Bad file descriptor
```

Thanks @agriyakhetarpal and @rgommers!

**Comment by hoodmane** [comment] 2024-02-22 16:55
A slightly simpler reproducer:
```py
from numpy.lib import format

with open("pywt/pywt/data/ecg.npy", "rb") as fid:
    format.read_array(fid)
```

**Comment by hoodmane** [comment] 2024-02-22 17:02
And another layer in:
```
import numpy as np

with open("pywt/pywt/data/ecg.npy", "rb") as fid:
    np.fromfile(fid, dtype=np.int32, count=1024)
```

**Comment by hoodmane** [comment] 2024-02-22 17:05
And inside of `array_fromfile` we encounter our nemesis, `dup2`:
https://github.com/numpy/numpy/blob/main/numpy/_core/src/multiarray/multiarraymodule.c?plain=1#L2348

**Comment by hoodmane** [comment] 2024-02-22 17:09
Can you tell me @rgommers why it is that the function called `npy_PyFile_Dup2` calls `os.dup` and not `os.dup2`?
https://github.com/numpy/numpy/blob/main/numpy/_core/include/numpy/npy_3kcompat.h?plain=1#L246

**Comment by rgommers** [comment] 2024-02-22 17:19
Great question. Git blame tells me that that line of code has not been touched in 15 years. Given the name, it's not unlikely that it was a simple error that didn't matter on other platforms. From your comments I assume you've run into `dup`/`dup2` before? 

Both are documented as "not available for WASI": https://docs.python.org/3/library/os.html#os.dup. No statement on WASM.

**Comment by rgommers** [comment] 2024-02-22 17:22
From the numpy 1.8.1 release notes:

_"The utility function `npy_PyFile_Dup` and `npy_PyFile_DupClose` are broken by the internal buffering python 3 applies to its file objects. To fix this two new functions `npy_PyFile_Dup2` and `npy_PyFile_DupClose2` are declared in `npy_3kcompat.h` and the old functions are deprecated. Due to the fragile nature of these functions it is recommended to instead use the python API when possible."_

So the `Dup2` here may not have meant the Python-level `dup2`.

**Comment by hoodmane** [comment] 2024-02-22 17:34
> From your comments I assume you've run into dup/dup2 before?

Yeah there have been at least five other bugs involving dup. At this point it's the first thing I expect when I see a bug report like this.
https://github.com/emscripten-core/emscripten/pulls?q=is%3Apr+author%3A%40me+dup

> So the Dup2 here may not have meant the Python-level dup2.

As you say, it seems not.

**Comment by hoodmane** [comment] 2024-02-22 17:44
Anyways I found the bug. Emscripten's filesystem maintains separate file descriptors from the host, so it has a mapping from the internal file descriptor to the host file descriptor. In the reproduction, the file is opened and linux assigns it descriptor 27, Emscripten assigns it descriptor 3. When we `dup` the descriptor, Emscripten makes a new descriptor 4, also pointing to linux descriptor 27. Then when we close emscripten descriptor 4 which closes linux descriptor 27 and finally when emscripten descriptor 3 is closed it tries to close linux descriptor 27 again which raises `EBADF: close() on bad file descriptor` which propagates into the OS error you see. We either need to also do a native `dup` on the linux descriptor or reference count it.

**Comment by hoodmane** [comment] 2024-02-23 11:30
I'll make a pr backporting the patch and ading a test case and close when that is merged.

**Closed** 2024-02-24 19:34 UTC
Labels: bug
