### ISSUE TITLE
Memory access out of bounds when creating pandas dataframe

### ISSUE THREAD

**Issue by dmondev** [pyodide/pyodide#1507] opened 2021-04-20 16:55 UTC
### Description
Uncaught RuntimeError: memory access out of bounds when creating pandas dataframe, with numpy.arange or dictionaries

#### Live Demo
https://codepen.io/dmondev/pen/gOgBWEp.

Each block in this codepen tests a pyodide usage scenario. Errors are displayed along with the python code executed.

This codepen uses a web worker with inline Blob to execute the python code.

### Versions
Chrome Version 90.0.4430.72 (Official Build) (64-bit)
Windows 10 1909 build 18363.1440

### Error
```
Uncaught RuntimeError: memory access out of bounds
    at __static_1 (<anonymous>:wasm-function[174]:0x17748)
    at byn$fpcast-emu$__static_1 (<anonymous>:wasm-function[506]:0x87748)
    at __static_2 (<anonymous>:wasm-function[175]:0x17eca)
    at __static_199 (<anonymous>:wasm-function[339]:0x538d5)
    at byn$fpcast-emu$__static_199 (<anonymous>:wasm-function[704]:0x881f7)
    at __static_254 (https://cdn.jsdelivr.net/pyodide/dev/full/pyodide.asm.wasm:wasm-function[901]:0x1d3efc)
    at byn$fpcast-emu$__static_254 (https://cdn.jsdelivr.net/pyodide/dev/full/pyodide.asm.wasm:wasm-function[21696]:0x7bc708)
    at _PyObject_GenericGetAttrWithDict (https://cdn.jsdelivr.net/pyodide/dev/full/pyodide.asm.wasm:wasm-function[1713]:0x218614)
    at PyObject_GenericGetAttr (https://cdn.jsdelivr.net/pyodide/dev/full/pyodide.asm.wasm:wasm-function[1712]:0x2183c9)
    at byn$fpcast-emu$PyObject_GenericGetAttr (https://cdn.jsdelivr.net/pyodide/dev/full/pyodide.asm.wasm:wasm-function[14359]:0x7a2290)
```

**Comment by hoodmane** [comment] 2021-04-21 01:40
The Python traceback says
```
Stack (most recent call first):
File "/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 1661 in is_unique
File "/lib/python3.8/site-packages/pandas/io/json/_json.py", line 214 in _format_axes
File "/lib/python3.8/site-packages/pandas/io/json/_json.py", line 131 in __init__
File "/lib/python3.8/site-packages/pandas/io/json/_json.py", line 76 in to_json
File "/lib/python3.8/site-packages/pandas/core/generic.py", line 2352 in to_json
```

**Comment by hoodmane** [comment] 2021-04-21 01:48
This is the same problem that is causing pandas test_load_largish file to fail. But I couldn't reproduce that outside of the test suite. There the traceback is:
```py
Stack (most recent call first):
  File "/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 1661 in is_unique
  File "/lib/python3.8/site-packages/pandas/core/frame.py", line 892 in items
  File "/lib/python3.8/site-packages/pandas/io/json/_json.py", line 1121 in _process_converter
  File "/lib/python3.8/site-packages/pandas/io/json/_json.py", line 1175 in _try_convert_dates
  File "/lib/python3.8/site-packages/pandas/io/json/_json.py", line 1140 in _try_convert_types
  File "/lib/python3.8/site-packages/pandas/io/json/_json.py", line 863 in parse
  File "/lib/python3.8/site-packages/pandas/io/json/_json.py", line 753 in _get_object_parser
  File "/lib/python3.8/site-packages/pandas/io/json/_json.py", line 731 in read
  File "/lib/python3.8/site-packages/pandas/io/json/_json.py", line 608 in read_json
```
and
```js
at __static_1 (<anonymous>:wasm-function[174]:0x17748)
at byn$fpcast-emu$__static_1 (<anonymous>:wasm-function[506]:0x87748)
at __static_2 (<anonymous>:wasm-function[175]:0x17eca)
at __static_199 (<anonymous>:wasm-function[339]:0x538d5)
at byn$fpcast-emu$__static_199 (<anonymous>:wasm-function[704]:0x881f7)
at __static_254 (http://127.0.0.1:44267/pyodide.asm.wasm:wasm-function[901]:0x1d3efc)
at byn$fpcast-emu$__static_254 (http://127.0.0.1:44267/pyodide.asm.wasm:wasm-function[21696]:0x7bc708)
at _PyObject_GenericGetAttrWithDict (http://127.0.0.1:44267/pyodide.asm.wasm:wasm-function[1713]:0x218614)
at PyObject_GenericGetAttr (http://127.0.0.1:44267/pyodide.asm.wasm:wasm-function[1712]:0x2183c9)
at byn$fpcast-emu$PyObject_GenericGetAttr (http://127.0.0.1:44267/pyodide.asm.wasm:wasm-function[14359]:0x7a2290)
at PyObject_GetAttr (http://127.0.0.1:44267/pyodide.asm.wasm:wasm-function[1701]:0x217362)
... (TONS more frames)
```

**Comment by hoodmane** [comment] 2021-04-21 01:48
Like the others, doesn't happen when devtools is open.

**Comment by jmsmdy** [comment] 2021-05-02 18:36
For this codepen to work on the latest dev version, you need to add `await pyodide.loadPackage(['numpy', 'pandas']);` after `await loadPyodide({ indexURL });`.

**Comment by hoodmane** [comment] 2021-05-02 18:39
Thanks to #1538 =)

**Comment by dmondev** [comment] 2021-05-04 13:56
Thanks, @jmsmdy, I updated the codepen.

**Comment by aadereiko** [comment] 2021-05-19 18:15
I face the same issue when I run the code snippet below:

```
import pandas
import plotly.express as px

df = px.data.iris()
fig = px.scatter(
df, x="sepal_width", y="sepal_length",
color="species")

fig
```

`await pyodide.loadPackage(['numpy', 'pandas', 'plotly'])` hasn't solved this issue

**Comment by MischaPanch** [comment] 2021-05-19 20:49
I faced similar issues with a slightly older version of pyodide. It is quite upsetting that this disappears when devtools are open, I though my app was fine because I only looked at it with open devtools during the package loading phase. 
@hoodmane Just out of curiosity, do you know what causes this Schroedinger-bug behavior?

**Comment by rth** [comment] 2021-05-19 20:55
As mentioned in https://github.com/pyodide/pyodide/issues/1507#issuecomment-823507692 in it's very likely a bug in Chrome. Could you try with Chrome 91 beta which hopefully would resolve this (91 stable release is on May 25)?

**Comment by aadereiko** [comment] 2021-05-19 21:43
@rth 
it seems like it's a bug of chrome 
thanks

**Comment by hoodmane** [comment] 2021-05-19 21:49
> @hoodmane Just out of curiosity, do you know what causes this Schroedinger-bug behavior?

It seems to be a mistake deep inside of the optimizing JIT of Chrome. We asked the Chrome devs and they aren't sure either:

> I think what is going on is that this code generates an erroneous effect/control chains in the Turbofan graph. This is because some instance fields are created and cached with their current effect and control inputs, but later used in different places, where these inputs might not be valid. It is not clear to me how exactly this results in the actual bug. In any case, this code has been streamlined since and this issue should be fixed. As expected, we cannot reproduce it in later versions.

From our chrome bug report:
https://bugs.chromium.org/p/chromium/issues/detail?id=1200031

**Comment by hoodmane** [comment] 2021-05-19 21:50
Presumably when devtools are open, the problematic optimizations are disabled.

**Comment by MischaPanch** [comment] 2021-05-20 08:52
> > @hoodmane Just out of curiosity, do you know what causes this Schroedinger-bug behavior?
> 
> It seems to be a mistake deep inside of the optimizing JIT of Chrome. We asked the Chrome devs and they aren't sure either:
> 
> > I think what is going on is that this code generates an erroneous effect/control chains in the Turbofan graph. This is because some instance fields are created and cached with their current effect and control inputs, but later used in different places, where these inputs might not be valid. It is not clear to me how exactly this results in the actual bug. In any case, this code has been streamlined since and this issue should be fixed. As expected, we cannot reproduce it in later versions.
> 
> From our chrome bug report:
> https://bugs.chromium.org/p/chromium/issues/detail?id=1200031

Thank you for the explanation! This definitely comes on my top 10 list of bugs that I could not have imagined.

**Comment by dmondev** [comment] 2021-05-25 21:16
Just to confirm, Google already released v91 as stable, and I'm no longer able to reproduce the bug from the codepen above (with 0.17.0).

**Comment by agriyakhetarpal** [comment] 2024-11-22 22:01
Thanks for checking, @dmondev! I think we can close this now, since you mention that this can't be reproduced and that the upstream issue in V8 and Chrome (https://issues.chromium.org/issues/40761565) has been fixed, too, since Chromium 91/92 and later. Please let us know in case you face any more problems with Pyodide or any package in specific. :)

**Closed by agriyakhetarpal** 2024-11-22 22:01 UTC
Labels: Fatal Error
