### ISSUE TITLE
Pyodide fails to load after require.js

### ISSUE THREAD

**Issue by seragunn** [pyodide/pyodide#4863] opened 2024-06-14 21:24 UTC
## 🐛 Bug

When loading require.js before Pyodide, calling `loadPyodide` results in an error: `Uncaught (in promise) TypeError: z.default.parse is not a function`

This corresponds to https://github.com/pyodide/pyodide/blob/f1acd57a54aaeaf92cbb4e3a5d8768c4e25ccc83/src/js/compat.ts#L263

No error occurs if Pyodide is loaded first (at least not apparently).

### To Reproduce

It's pretty much the [first example in the docs](https://pyodide.org/en/stable/usage/quickstart.html#complete-example) but with `requirejs` loaded ahead of pyodide. I'm loading pyodide in a module as that helps track the source but the error is the same even without modules.

```html
<!doctype html>
<html>

<head>
  <script src="https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js"></script>

  <script type="module">
    import { loadPyodide } from "https://cdn.jsdelivr.net/pyodide/v0.26.1/full/pyodide.mjs"

    async function main() {
      let pyodide = await loadPyodide();
      console.log(pyodide.runPython(`
              import sys
              sys.version
          `));
      let output = pyodide.runPython("1 + 2");
      document.getElementById("py-out").innerText = output;
    }
    main().catch((e) => {
      document.getElementById("py-out").innerText = "Error";
    });

    // export main so it can be tested in the dev console
    globalThis.main = main;
  </script>
</head>

<body>
  <div id="py-out">Running...</div>
</body>

</html>
```

### Expected behavior

Pyodide should load 

### Environment

- Pyodide Version 0.26.1
- Browser version Firefox 127.0/Linux and Chromium 126.0.6478.55/Linux
- Any other relevant information:

Platform: Arch Linux

### Additional context

I tested this with each version of Pyodide from v0.21.0 onward. The latest version of Pyodide which is compatible seems to be 0.23.4

**Comment by ryanking13** [comment] 2024-06-15 02:08
This is because loading require.js has a side effect of defining `define`, and `define.amd` variables, and ErrorStackParser assumes that it is in CommonJS environment when `define` is defined ([code pointer](https://github.com/stacktracejs/error-stack-parser/blob/9f33c224b5d7b607755eb277f9d51fcdb7287e24/error-stack-parser.js#L7), [another related issue](https://github.com/pyodide/pyodide/issues/4577)).

I get a headache when I see all this commonjs, umd, and amd stuff. I think it would be a good idea to remove the legacy code from the error-stack-parser and just embed the necessary parts into pyodide.

**Comment by ryanking13** [comment] 2024-06-15 03:24
cc: @RulerOfCakes I wonder if you have some experience in dealing with this kind of CommonJS / AMD issues.

**Comment by RulerOfCakes** [comment] 2024-06-15 10:02
Although I'm also not that familiar with these types of module conflict issues, it seems that esbuild isn't exactly friendly with the UMD syntax(https://github.com/evanw/esbuild/issues/507), hence the UMD syntax 'leaking out' even from an ESM build of pyodide is non trivial to avoid. With the AMD globals present in the environment as you have pointed out, this ends up resolving to an AMD export. I'm not sure if there are any trivial fixes aside from embedding the dependency itself or messing around with regexes in the build step, or forcefully removing the AMD globals in the build output.


A better/safer way to prevent these types of unexpected conflicts caused by globals in the future would perhaps be something like using the upcoming [ShadowRealm](https://github.com/tc39/proposal-shadowrealm) API, which is under development for [V8](https://issues.chromium.org/issues/41480387) / [Node](https://github.com/nodejs/node/issues/42528).

**Comment by ryanking13** [comment] 2024-06-17 10:52
I see. Thanks for the help. I'll see if I can vendor error-stack-parser.

**Closed** 2024-06-18 10:59 UTC
Labels: bug
