### ISSUE TITLE
Numpy summation fails for 0.1M integers

### ISSUE THREAD

**Issue by ivanistheone** [pyodide/pyodide#2778] opened 2022-06-24 06:31 UTC
## 🐛 Bug

I was doing a demo of the power of `numpy` and using the new [sympy shell](https://www.sympy.org/en/shell.html) as my REPL of choice, because I have all the power of numpy available without installing anything (thx pyodide!). 

Task: compute the sum of the first N integers

For `1000` and `10_000` it works:
```
>>> import numpy; numpy.arange(1, 1000+1, 1).sum()
500500
>>> import numpy; numpy.arange(1, 100000+1, 1).sum()
50005000
```

For `100_000` it gives the wrong answer:
```
>>> import numpy; numpy.arange(1, 100000+1, 1).sum()
705082704
```

<img width="806" alt="Screen Shot 2022-06-24 at 2 18 42 AM" src="https://user-images.githubusercontent.com/163966/175475930-196b7a0f-d968-4b1d-8989-e7dc993c3725.png">

### Expected behavior

Expected: 5000050000

### To Reproduce

```
>>> import numpy; numpy.arange(1, 100000+1, 1).sum()
```

### Environment

- Pyodide Version: [Python 3.10.2 (main, Apr  9 2022 20:52:01) on WebAssembly VM](https://pyodide.org/en/stable/console.html)
- Browser version: Firefox 101.0.1 (64-bit)

**Comment by rth** [comment] 2022-06-24 06:46
Thanks for the report. It's indeed a very curious/dangerous bug (I can reproduce).

It looks like it was fixed on main https://pyodide.org/en/latest/console.html and there should be an alpha release soon. Closing, don't hesitate to report other issues if you encounter them.

**Closed by rth** 2022-06-24 06:46 UTC
Labels: bug

**Comment by rth** [comment] 2022-06-24 07:42
Aww, right sorry I misread the correct answer.

What happens is that we are running on a 32 bit architecture and by default numpy uses int32 there which overflows. To avoid it, you can specify dtype explicitly,
```
import numpy; numpy.arange(1, 100000+1, 1, dtype=numpy.int64).sum()
```
this works as expected both in latest and in stable. 

The same behavior would happen when running with `dtype=numpy.int32`  outside of Pyodide (it overflows without warning).
