### ISSUE TITLE
Loading a module doesn't cause imported packages to load

### ISSUE THREAD

**Issue by wch** [pyodide/pyodide#2547] opened 2022-05-11 21:34 UTC
## 🐛 Bug

When loading a module, if that module has any `import` statements, they don't actually cause pyodide to load the package

### To Reproduce

In the Pyodide console, run:

```py
import os
os.makedirs("foo", exist_ok=True)
with open("foo/bar.py", "w") as f:
    f.write("import numpy\nprint(numpy.add(1, 2))\n")

import foo.bar
```

It prints:

```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/pyodide/foo/bar.py", line 1, in <module>
    import numpy
ModuleNotFoundError: No module named 'numpy'
```

### Expected behavior

It should do print `3`:

```
>>> import foo.bar
3
```

This happens not only for custom modules that are created on the VFS. It can also happen for packages which don't take a hard dependency on another package, but instead `import` them at run time. For example, you might have a function in a package that calls `import matplotlib`, but you don't necessarily want to always load matplotlib when the package loads.

### Environment

- Pyodide Version: 0.20.1a1
- Browser version: 100.0.4896.127

**Comment by hoodmane** [comment] 2022-05-11 21:37
This is the intended behavior. I do not believe that fixing this is even possible, let alone desirable. Load `numpy` with `pyodide.loadPackage` or `micropip.install` before trying to use it.

**Comment by hoodmane** [comment] 2022-05-11 21:39
In principle, you could catch `ImportError` and call `pyodide.loadPackage` and it might work if there are no side effects. But we run into trouble that Python code can do arbitrarily complicated nonsense so there is no way to figure out if it tries to import numpy without executing it. But executing code causes side effects and catching the error, loading numpy, then trying again may cause havoc.

**Comment by wch** [comment] 2022-05-11 22:35
I know this is already labeled as `wont-fix` but here's an example:

```py
import pandas as pd
df = pd.DataFrame({
    'length': [1.5, 0.5, 1.2, 0.9, 3],
    'width': [0.7, 0.2, 0.15, 0.2, 1.1]
    })
df.hist(bins=3)
```

With "normal" Python this will return the following object:

```
array([[<AxesSubplot:title={'center':'length'}>,
        <AxesSubplot:title={'center':'width'}>]], dtype=object)
```

But with Pyodide it throws an error:

```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/lib/python3.10/site-packages/pandas/plotting/_core.py", line 225, in hist_frame
    plot_backend = _get_plot_backend(backend)
  File "/lib/python3.10/site-packages/pandas/plotting/_core.py", line 1849, in _get_plot_backend
    module = _load_backend(backend)
  File "/lib/python3.10/site-packages/pandas/plotting/_core.py", line 1787, in _load_backend
    raise ImportError(
ImportError: matplotlib is required for plotting when the default backend "matplotlib" is selected.
```

This is because the `.hist()` method loads matplotlib (https://github.com/pandas-dev/pandas/blob/a853022ea154dd38dd759300ee50b456f3a9ddf6/pandas/plotting/_matplotlib/hist.py#L370)

```py
    import matplotlib.pyplot as plt
```

I don't know anything about Pyodide's internals, but perhaps it's possible to hook into Python's `import` machinery so that it tells Pyodide to load the package?

**Comment by rth** [comment] 2022-05-11 22:59
@wch If you install pandas alone outside of Pyodide, you would get exactly the same behavior because matplotlib is an optional dependency https://pandas.pydata.org/docs/getting_started/install.html#optional-dependencies and needs to be explicitly installed.

The solution is still to install the required packages explicitly.

Generally, we are exposing exactly what normal Python does. Installing packages from import names in some cases where we determine it's safe to do so is the exception rather than the norm. In most cases though you need to install packages you need (with `micropip`), exactly as you would with a  regular Python.

Sorry, I'm going to close this as won't fix.

**Closed by rth** 2022-05-11 22:59 UTC
Labels: bug, wont-fix

**Comment by hoodmane** [comment] 2022-05-11 23:04
> but perhaps it's possible to hook into Python's import machinery so that it tells Pyodide to load the package?

The problem is that Python's import machinery is synchronous and loading the package is asynchronous.

**Comment by wch** [comment] 2022-05-12 00:07
> @wch If you install pandas alone outside of Pyodide, you would get exactly the same behavior because matplotlib is an optional dependency [pandas.pydata.org/docs/getting_started/install.html#optional-dependencies](https://pandas.pydata.org/docs/getting_started/install.html#optional-dependencies) and needs to be explicitly installed.

The assumption behind the example above is that pandas and matplotlib are already installed -- that's true on my regular python installation as well as on pyodide. Normally, the `df.hist()` call causes it to _load_ matplotlib, but on pyodide it doesn't.

To show that the behavior is not the same between the two, here's a screenshot of the two side-by-side (pyodide on the left):
<img width="1109" alt="image" src="https://user-images.githubusercontent.com/86978/167966572-0bd1d370-e923-4b3a-b7c7-e0f92b927150.png">

Again, both pandas and matplotlib are already installed on both platforms.

> The solution is still to install the required packages explicitly.
>
> Generally, we are exposing exactly what normal Python does. Installing packages from import names in some cases where we determine it's safe to do so is the exception rather than the norm. In most cases though you need to install packages you need (with `micropip`), exactly as you would with a regular Python.

Even if I tell pyodide to install matplotlib (via `micropip.install('matplotlib')`), that won't automatically make it available for pandas to load it when `df.hist()` is called.

The issue is not automatic installation of packages, it's the _loading_ of packages from code in a module.

**Comment by hoodmane** [comment] 2022-05-12 00:14
> The assumption behind the example above is that pandas and matplotlib are already installed.

In my opinion if a program is "installed" that means it is already on my machine. When I run an "installed" program I expect it to be loaded from my local disk, not downloaded over the network. If the program needs to be downloaded, it isn't installed yet. 

In Pyodide `matplotlib` is not installed. To fix that, a network request has to be made. All "mandatory dependencies" of `pandas` are installed automatically, but `pandas` lists `matplotlib` as an "optional dependency" so it isn't installed automatically. You can force it to be installed with `pyodide.loadPackage(["matplotlib", "pandas"]);` or by `import matplotlib`. 

The concept of "optional dependency" is a bit of a bizarre oxymoron though.

**Comment by hoodmane** [comment] 2022-05-12 00:18
Here is the same behavior in a native Python: 
1. create a new virtual environment
2. `pip install pandas`
3. Try to use `df.hist`:
![image](https://user-images.githubusercontent.com/8739626/167967665-eef5f12f-fe90-433d-ba89-3334fb2faa3d.png)

**Comment by ryanking13** [comment] 2022-05-12 01:30
> Even if I tell pyodide to install matplotlib (via `micropip.install('matplotlib')`), that won't automatically make it available for pandas to load it when `df.hist()` is called.

Hmm, I think that is not true, could you give us a reproducible example? I can't reproduce it in Pyodide console.

```py
# In: https://pyodide.org/en/latest/console.html
>>> import matplotlib, pandas as pd # 
>>> df = pd.DataFrame({
    'length': [1.5, 0.5, 1.2, 0.9, 3],
    'width': [0.7, 0.2, 0.15, 0.2, 1.1]
    })
>>> df.hist(bins=3)
array([[<AxesSubplot:title={'center':'length'}>,
        <AxesSubplot:title={'center':'width'}>]], dtype=object)
```

**Comment by ryanking13** [comment] 2022-05-12 01:43
> I don't know anything about Pyodide's internals, but perhaps it's possible to hook into Python's `import` machinery so that it tells Pyodide to load the package?

As @hoodmane mentioned, there is an issue with the synchronous import and asynchronous package loading system.

About import hooks, there was a discussion (#1917), and [a reference implementation](https://github.com/ryanking13/pyodide-importer). However, I think its usage is quite limited [as there are some limitations on synchronous requests in the main thread (and it is deprecated)](https://developer.mozilla.org/ko/docs/Web/API/XMLHttpRequest/Synchronous_and_Asynchronous_Requests#synchronous_request)

**Comment by rth** [comment] 2022-05-12 01:43
I think some of the confusion in this thread comes from the way packages are installed in Pyodide.
When you start a Pyodide REPL nothing is installed aside from the stdlib.  By installed I mean present on the file system. To use pandas etc these packages need installed with micropip. As one would do with standard python when starting in a new virtualenv. 

Except that we do some magic with parsing the imports and installing the packages from import names (only for packages built in Pyodide). It's transparent to the user, but packages are still installed. It's just an implicit mechanism.
So when @ryanking13 put both pandas and maptotlib imports in the REPL, that's equivalent to running `micropip.install` on both packages. 

So the overall message is if you need any package, you need to install it.  Whether it happens by parsing imports in the REPL or explicit micropip.install calls. Pyodide comes with 0 packages installed by default.

**Comment by wch** [comment] 2022-05-13 01:08
> Except that we do some magic with parsing the imports and installing the packages from import names (only for packages built in Pyodide). It's transparent to the user, but packages are still installed. It's just an implicit mechanism.

@rth Thanks for clarifying -- it makes sense now.
