### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'atime')

### ISSUE THREAD

**Issue by rth** [pyodide/pyodide#3795] opened 2023-04-25 20:42 UTC
Report by @darrint on Gitter, 

> I'm reporting this error as requested by an error message from pyodide. I received this while working with JupyterLite. I was working on a notebook and everything was fine. At some point, I don't remember what I did but I think I was messing with pip install, I could no longer run python code. I found this in the browser console:

```
 Uncaught (in promise) TypeError: Cannot destructure property 'path' of 'a' as it is null.
    at I._onMessage (302.8bcc38f.js:1:15395)
pyodide.asm.js:9  Pyodide has suffered a fatal error. Please report this to the Pyodide maintainers.
API.fatal_error @ pyodide.asm.js:9
pyodide.asm.js:9  The cause of the fatal error was:
API.fatal_error @ pyodide.asm.js:9
pyodide.asm.js:9  TypeError: Cannot read properties of null (reading 'atime')
    at mi.getattr (951.b9fa6250974e699a3731.js?v=b9fa6250974e699a3731:2:155996)
    at hi.getattr (951.b9fa6250974e699a3731.js?v=b9fa6250974e699a3731:2:153211)
    at stat (pyodide.asm.js:9:215160)
    at Object.doStat (pyodide.asm.js:9:235312)
    at ___syscall_stat64 (pyodide.asm.js:9:277194)
    at pyodide.asm.wasm:0x430c43
    at pyodide.asm.wasm:0x449d13
    at pyodide.asm.wasm:0x381a67
    at pyodide.asm.wasm:0x3812ff
    at pyodide.asm.wasm:0x2654b4
API.fatal_error @ pyodide.asm.j
```

Thanks for the report! Sounds like a file-system related issue when calling the stat64 syscall / atime. 
I don't really have many ideas currently but opening this issue for future reference.

**Comment by ryanlovett** [comment] 2023-05-02 20:47
I ran across something similar when I tried to embed JupyterLite into a [Page](https://community.canvaslms.com/t5/Canvas-Basics-Guide/What-are-Pages/ta-p/5) in a Canvas LMS site.
```html
<iframe
  src="https://jupyterlite.github.io/demo/repl/index.html?kernel=python&toolbar=1"
  width="100%"
  height="500px"
>
</iframe>
```

The jupyterlite appeared to render fine, and I entered a couple of lines of code into a jupyter code cell, but the kernel never returned. Chrome's console had:

```
pyodide.asm.js:9 Pyodide has suffered a fatal error. Please report this to the Pyodide maintainers.
API.fatal_error @ pyodide.asm.js:9
pyodide.asm.js:9 The cause of the fatal error was:
API.fatal_error @ pyodide.asm.js:9
pyodide.asm.js:9 TypeError: Cannot read properties of null (reading 'atime')
    at mi.getattr (worker.js:7:4645)
    at hi.getattr (worker.js:7:1854)
    at stat (pyodide.asm.js:9:215160)
    at Object.doStat (pyodide.asm.js:9:235312)
    at ___syscall_stat64 (pyodide.asm.js:9:277194)
    at pyodide.asm.wasm:0x430c43
    at pyodide.asm.wasm:0x449d13
    at pyodide.asm.wasm:0x381a67
    at pyodide.asm.wasm:0x3812ff
    at pyodide.asm.wasm:0x2654b4
Stack (most recent call first):
pyodide.asm.js:9   File "<frozen importlib._bootstrap_external>", line 147 in _path_stat
pyodide.asm.js:9   File "<frozen zipimport>", line 75 in __init__
pyodide.asm.js:9   File "<frozen importlib._bootstrap_external>", line 1415 in _path_hooks
pyodide.asm.js:9   File "<frozen importlib._bootstrap_external>", line 1439 in _path_importer_cache
pyodide.asm.js:9   File "<frozen importlib._bootstrap_external>", line 1473 in _get_spec
pyodide.asm.js:9   File "<frozen importlib._bootstrap_external>", line 1504 in find_spec
pyodide.asm.js:9   File "<frozen importlib._bootstrap>", line 1080 in _find_spec
pyodide.asm.js:9   File "<frozen importlib._bootstrap>", line 1143 in _find_and_load_unlocked
pyodide.asm.js:9   File "<frozen importlib._bootstrap>", line 1181 in _find_and_load
pyodide.asm.js:9   File "<frozen importlib._bootstrap>", line 1209 in _gcd_import
pyodide.asm.js:9   File "/lib/python311.zip/importlib/__init__.py", line 126 in import_module
pyodide.asm.js:9   File "/lib/python3.11/site-packages/IPython/core/extensions.py", line 91 in _load_extension
pyodide.asm.js:9   File "/lib/python3.11/site-packages/IPython/core/extensions.py", line 76 in load_extension
pyodide.asm.js:9   File "/lib/python3.11/site-packages/IPython/core/shellapp.py", line 282 in init_extensions
pyodide.asm.js:9   File "/lib/python3.11/site-packages/pyodide_kernel/interpreter.py", line 72 in initialize
pyodide.asm.js:9   File "/lib/python3.11/site-packages/pyodide_kernel/__init__.py", line 27 in <module>
pyodide.asm.js:9   File "<frozen importlib._bootstrap>", line 241 in _call_with_frames_removed
pyodide.asm.js:9   File "<frozen importlib._bootstrap_external>", line 940 in exec_module
pyodide.asm.js:9   File "<frozen importlib._bootstrap>", line 690 in _load_unlocked
pyodide.asm.js:9   File "<frozen importlib._bootstrap>", line 1152 in _find_and_load_unlocked
pyodide.asm.js:9   File "<frozen importlib._bootstrap>", line 1181 in _find_and_load
pyodide.asm.js:9   File "<exec>", line 6 in <module>
pyodide.asm.js:9   File "/lib/python311.zip/_pyodide/_base.py", line 365 in run_async
pyodide.asm.js:9   File "/lib/python311.zip/_pyodide/_base.py", line 540 in eval_code_async
pyodide.asm.js:9   File "/lib/python311.zip/asyncio/events.py", line 80 in _run
pyodide.asm.js:9   File "/lib/python311.zip/pyodide/webloop.py", line 319 in run_handle
```

**Comment by ryanlovett** [comment] 2023-05-02 21:01
Sorry for the noise. This was a simple case of a browser extension (ublock origin) preventing this from loading properly. After disabling it and force reloading, jupyterlite/pyodide work just fine.

**Comment by hoodmane** [comment] 2023-05-02 21:05
Well it's interesting to hear that a second person saw this error. It's due to an invalid or null file object or file stream. But it's hard to investigate until someone finds a reproduction. And there's a pretty good chance it's a downstream bug of some sort...

**Comment by rth** [comment] 2023-05-02 21:29
Because both cases were with Jupyterlite, it's also possible this has something do to with the fact that it uses a separate filesystem for the home repository [`DriveFS`](https://github.com/jupyterlite/jupyterlite/blob/2ee9cba529cb514c00130924c355d8696fd4562c/packages/contents/src/drivefs.ts#L91) (inspired by BrowserFS) for notebook persistence which from my limited exposure to it, seems to be less POSIX compliant in some case than TEMPFS. Or at least  sqlite for instance would crash when used with it https://github.com/jupyterlite/pyodide-kernel/issues/35

Opened https://github.com/jupyterlite/jupyterlite/issues/1071 as a general issue about it.

**Comment by hoodmane** [comment] 2023-05-02 21:37
I wonder why they don't use idbfs...

**Comment by andeplane** [comment] 2023-05-09 09:34
I've gotten similar issues (sometimes I see the `reading 'atime'` error too), and reported my findings here https://github.com/jupyterlite/jupyterlite/issues/1074

It seems like a message with the wrong structure is being picked up and parsed.

**Comment by hoodmane** [comment] 2023-05-09 15:04
I will close this for now because it's very probably a downstream issue with JupyterLite. If anything suggests this might be a bug in Pyodide itself, I can reopen it.

**Closed by hoodmane** 2023-05-09 15:04 UTC
Labels: bug
