### ISSUE TITLE
http.pyfetch fails in Node.js

### ISSUE THREAD

**Issue by rth** [pyodide/pyodide#2497] opened 2022-05-05 01:27 UTC
When calling http.pyfetch in Node.js, I get,
```py
PythonError: Traceback (most recent call last):
  File "/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/lib/python3.10/asyncio/tasks.py", line 232, in __step
    result = coro.send(None)
  File "/lib/python3.10/site-packages/_pyodide/_base.py", line 500, in eval_code_async
    await CodeRunner(
  File "/lib/python3.10/site-packages/_pyodide/_base.py", line 353, in run_async
    await coroutine
  File "<exec>", line 3, in <module>
  File "/lib/python3.10/site-packages/pyodide/http.py", line 228, in pyfetch
    from js import fetch as _jsfetch
ImportError: cannot import name 'fetch' from 'js' (unknown location)
```

Likely because in this case, we need to use the node-fetch rather than the JS fetch.

**Comment by amitsaha** [comment] 2022-06-06 07:42
I will have a look at this one.

**Comment by amitsaha** [comment] 2022-06-15 20:47
Hi @rth trying to reproduce this with a build from `main` branch with the following script:

```$ cat test.js 
async function pyfetchDemo() {
  let pyodide_pkg = await import("pyodide/pyodide.js");
  let pyodide = await pyodide_pkg.loadPyodide();
  console.log(await pyodide.runPythonAsync(`
    from pyodide.http import pyfetch
    response = await pyfetch("https://github.com")
    print(await response.bytes());
   `));
}

pyfetchDemo();
```

The script executes successfully for me.  Am I missing something here?

*Details*

- `npm install pyodide`
- Build from sources of `main` branch, `cp -r dist/*.js node_modules/pyodide/`
- `node <test.js>`
- Output from Python

**Comment by ryanking13** [comment] 2022-06-16 00:09
Node added experimental `fetch` support from `v17.5.0`. Maybe it is enabled by default in `v18.3.0`?

Could you try `node --no-experimental-fetch` and `node --experimental-fetch` and see if the result differs?

**Comment by hoodmane** [comment] 2022-06-16 00:13
I have noticed we have some issues with fetch support. It seems like micropip doesn't use `node-fetch` correctly and will use the native fetch when it's available, whereas `loadPackage` only uses `node-fetch` and cannot use the native fetch even if it is available.

**Comment by amitsaha** [comment] 2022-06-16 09:21
Thanks @ryanking13 - you guessed it right.

With `node --no-experimental-fetch`:

``` File "<exec>", line 3, in <module>
  File "/lib/python3.10/site-packages/pyodide/http.py", line 228, in pyfetch
    from js import fetch as _jsfetch
ImportError: cannot import name 'fetch' from 'js' (unknown location)
```

With `node --experimental-fetch`, gives back successful result.

One straight forward approach could be to try `fetch` first and if we get an `ImportError`, attempt to import from `node-fetch`? Should it be the user's responsibility to then install `node-fetch` if they are not using `node >= 18.3.0` especially since it is enabled by default in `v18.3.0` (at least).

**Comment by ryanking13** [comment] 2022-06-16 23:22
> One straight forward approach could be to try `fetch` first and if we get an `ImportError`, attempt to import from `node-fetch`?

I'm +1 for it.

> Should it be the user's responsibility to then install `node-fetch` if they are not using `node >= 18.3.0` especially since it is enabled by default in `v18.3.0` (at least).

I think we already have `node-fetch` dependency in pyodide js package. So probably we can simply use it.

https://github.com/pyodide/pyodide/blob/648d9e18d60dbd266274f569773bc563ffb304b0/src/js/package.json#L122-L125

**Comment by hoodmane** [comment] 2022-06-16 23:24
I made an attempt in #2722 but it doesn't work.

**Comment by asaha123** [comment] 2022-06-20 02:33
> I made an attempt in #2722 but it doesn't work.

Looks like you attempted to replace it at a higher level than this issue is referring to as a way to unify all uses of the `fetch()` functionality?

**Comment by amitsaha** [comment] 2022-07-04 06:12
> I will have a look at this one.

Unfortunately, other tasks have caught up with me, so will not be working on this issue any further.

**Comment by ryanking13** [comment] 2024-06-29 08:17
We don't support Node.js < 18 anymore and Node.js >= 18 has native fetch so I believe this won't happen anymore. Closing.

**Closed by ryanking13** 2024-06-29 08:17 UTC
Labels: bug
