### ISSUE TITLE
Not all tests pass in main branch

### ISSUE THREAD

**Issue by albertas** [pyodide/pyodide#1560] opened 2021-05-01 06:15 UTC
I have cloned the master branch and ran these commands:
```
./run_docker
make
pytest src/ pyodide_build/ packages/*/test_*
```
And 29 tests failed:
```
=============================================================== short test summary info ===============================================================
FAILED test_bz2.py::bz2[firefox]
FAILED test_bz2.py::bz2[chrome]
FAILED test_core_python.py::cpython_core[test_zipfile-firefox] - conftest.JavascriptException: TypeError: Module._BZ2_bzDecompressInit is undefined
FAILED test_core_python.py::cpython_core[test_zipfile64-firefox] - conftest.JavascriptException: Error: Pyodide already fatally failed and can no lo...
FAILED test_core_python.py::cpython_core[test_zipimport-firefox] - conftest.JavascriptException: Error: Pyodide already fatally failed and can no lo...
FAILED test_core_python.py::cpython_core[test_zipimport_support-firefox] - conftest.JavascriptException: Error: Pyodide already fatally failed and c...
FAILED test_core_python.py::cpython_core[test_zlib-firefox] - conftest.JavascriptException: Error: Pyodide already fatally failed and can no longer ...
FAILED test_core_python.py::cpython_core[test_argparse-chrome] - selenium.common.exceptions.TimeoutException: Message: script timeout
FAILED test_core_python.py::cpython_core[test_zipfile-chrome] - conftest.JavascriptException: TypeError: Cannot read property 'apply' of undefined
FAILED test_core_python.py::cpython_core[test_zipfile64-chrome] - conftest.JavascriptException: Error: Pyodide already fatally failed and can no lon...
FAILED test_core_python.py::cpython_core[test_zipimport-chrome] - conftest.JavascriptException: Error: Pyodide already fatally failed and can no lon...
FAILED test_core_python.py::cpython_core[test_zipimport_support-chrome] - conftest.JavascriptException: Error: Pyodide already fatally failed and ca...
FAILED test_core_python.py::cpython_core[test_zlib-chrome] - conftest.JavascriptException: Error: Pyodide already fatally failed and can no longer b...
FAILED test_sqlite3.py::sqlite3[firefox]
FAILED test_sqlite3.py::sqlite3[chrome]
FAILED test_webworker.py::runwebworker_different_package_name[firefox] - selenium.common.exceptions.TimeoutException: Message: Timed out after 20000 ms
FAILED test_webworker.py::runwebworker_different_package_name[chrome] - selenium.common.exceptions.TimeoutException: Message: script timeout
FAILED test_webworker.py::runwebworker_no_imports[firefox] - selenium.common.exceptions.TimeoutException: Message: Timed out after 20000 ms
FAILED test_webworker.py::runwebworker_no_imports[chrome] - selenium.common.exceptions.TimeoutException: Message: script timeout
FAILED test_webworker.py::runwebworker_micropip[firefox] - selenium.common.exceptions.TimeoutException: Message: Timed out after 20000 ms
FAILED test_webworker.py::runwebworker_micropip[chrome] - selenium.common.exceptions.TimeoutException: Message: script timeout
FAILED nltk/test_nltk.py::nltk_edit_distance[firefox] - conftest.JavascriptException: TypeError: Module._sqlite3_libversion is undefined
FAILED nltk/test_nltk.py::nltk_jaccard_distance[firefox] - conftest.JavascriptException: Error: Pyodide already fatally failed and can no longer be ...
FAILED nltk/test_nltk.py::nltk_ngrams[firefox] - conftest.JavascriptException: Error: Pyodide already fatally failed and can no longer be used.
FAILED nltk/test_nltk.py::nltk_edit_distance[chrome] - conftest.JavascriptException: TypeError: Cannot read property 'apply' of undefined
FAILED nltk/test_nltk.py::nltk_jaccard_distance[chrome] - conftest.JavascriptException: Error: Pyodide already fatally failed and can no longer be u...
FAILED nltk/test_nltk.py::nltk_ngrams[chrome] - conftest.JavascriptException: Error: Pyodide already fatally failed and can no longer be used.
FAILED numpy/test_numpy.py::runwebworker_numpy[chrome] - selenium.common.exceptions.TimeoutException: Message: script timeout
FAILED pywavelets/test_pywt.py::pywt[chrome] - selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id
ERROR pywavelets/test_pywt.py::pywt[chrome] - selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id
============================= 29 failed, 1312 passed, 17 skipped, 258 xfailed, 86 warnings, 1 error in 2197.87s (0:36:37) =============================
```
CI pipeline steps does not match the standard testing procedure, i.e. `pytest src/ pyodide_build/ packages/*/test_*`. Probably CI uses some kind of magic wrapper which retries with fresh browser driver on fail. Could we provide the same testing command (as one used in the CI) in the documentation? So that I could make tests pass in master branch?

**Comment by hoodmane** [comment] 2021-05-01 07:23
> CI uses some kind of magic wrapper which retries with fresh browser driver on fail

Indeed:
https://github.com/pyodide/pyodide/blob/09ea322991f3088fdf05864d11ce377762186e80/.circleci/config.yml#L148
https://github.com/pyodide/pyodide/blob/main/tools/pytest_wrapper.py

> standard

Yes, it's weird and not standard. On the other hand, it seems like it's a technique that @dalcde probably copied from somewhere else. It makes a lot of sense as a simple way to handle slightly inconsistent tests. Now the trick is keeping the rest of the test suite only *slightly* inconsistent...

> provide same command in documentation?

If you want to add some sort of parenthetical note about this it'd probably be an improvement.

**Comment by hoodmane** [comment] 2021-05-01 07:24
Another important factor is that we manually "rerun from failed" a lot.

**Comment by hoodmane** [comment] 2021-05-01 07:29
We also only require the tests with `-k not chrome` to pass in order to deploy:
https://github.com/pyodide/pyodide/blob/main/.circleci/config.yml#L343

And on top of that, the run_webworker tests were persistently broken from ffa99153cc4ccb233ad11d3cd58108f06707d01f to eebd8d5453c5985204ff781837b67cfc4c74c4da (these webworker tests time out a ton even normally so it took a few days before @rth noticed that there was a consistent failure).

**Comment by albertas** [comment] 2021-05-01 09:58
I have executed this command inside container:
`tools/pytest_wrapper.py src packages/micropip/ -v -k firefox -n 3`
Still got a lot of tests failing (only 3 of them failed due to timeouts):
```
=============================================================== short test summary info ===============================================================
FAILED test_bz2.py::bz2[firefox]
FAILED test_core_python.py::cpython_core[test_zipfile-firefox] - conftest.JavascriptException: TypeError: Module._BZ2_bzDecompressInit is undefined
FAILED test_core_python.py::cpython_core[test_zipfile64-firefox] - conftest.JavascriptException: Error: Pyodide already fatally failed and can no lo...
FAILED test_core_python.py::cpython_core[test_zipimport-firefox] - conftest.JavascriptException: Error: Pyodide already fatally failed and can no lo...
FAILED test_core_python.py::cpython_core[test_zipimport_support-firefox] - conftest.JavascriptException: Error: Pyodide already fatally failed and c...
FAILED test_core_python.py::cpython_core[test_zlib-firefox] - conftest.JavascriptException: Error: Pyodide already fatally failed and can no longer ...
FAILED test_sqlite3.py::sqlite3[firefox]
FAILED test_typeconversions.py::bigint_conversions[firefox] - AttributeError: module 'numpy' has no attribute 'ndarray'
FAILED test_typeconversions.py::hyp_py2js2py[firefox] - AttributeError: module 'numpy' has no attribute 'ndarray'
FAILED test_typeconversions.py::hyp_tojs_no_crash[firefox] - AttributeError: module 'numpy' has no attribute 'ndarray'
FAILED test_typeconversions.py::string_conversion[firefox] - AttributeError: module 'numpy' has no attribute 'ndarray'
FAILED test_typeconversions.py::number_conversions[firefox] - AttributeError: module 'numpy' has no attribute 'ndarray'
FAILED test_webworker.py::runwebworker_different_package_name[firefox] - selenium.common.exceptions.TimeoutException: Message: Timed out after 20000 ms
FAILED test_webworker.py::runwebworker_no_imports[firefox] - selenium.common.exceptions.TimeoutException: Message: Timed out after 20000 ms
FAILED test_webworker.py::runwebworker_micropip[firefox] - selenium.common.exceptions.TimeoutException: Message: Timed out after 20000 ms
================================== 15 failed, 545 passed, 10 skipped, 126 xfailed, 67 warnings in 353.01s (0:05:53) ===================================
```
I want to develop a new feature. How could I know that these tests fail not due to my changes? 
I could simply mark these tests to be skipped for now.

**Comment by rth** [comment] 2021-05-01 10:07
> I have cloned the master branch

This might be the problem. There is no longer a master branch, it's now called main. So you need to rename the branch on your fork and sync with upstream main.  In particular `bigint_conversions` etc shouldn't need numpy, so it looks like you have an outdated version of the code.

**Comment by rth** [comment] 2021-05-01 10:17
Though no your fork looks OK. 

There are really two errors here which needs investigating,

> TypeError: Module._BZ2_bzDecompressInit is undefined

this failure makes all the following tests fail as well.

>  AttributeError: module 'numpy' has no attribute 'ndarray'

This one is strange and shouldn't be happening, and needs investigating.

Then there are some run_webworker failure which should go away if you re-run them (assuming you have the latest version from master).

> I want to develop a new feature. How could I know that these tests fail not due to my changes?

Well you know what fails now, so you would be able to see if there are any new failures. 
The tests in selenium are somewhat brittle, we are trying to make them better related to #1389 but it's still an ongoing effort.

Let me rebuild locally to see if I can reproduce.

**Comment by rth** [comment] 2021-05-01 10:42
Also the issue might be that we never actually doing a full `make` form the start, both in the CI and locally (because it takes to long). Usually we,
 1. first build core Pyodide + packages used in the core test suite https://github.com/pyodide/pyodide/blob/7cf5bd58095d6484d801cc535b11d60b13412a31/.circleci/config.yml#L75
 2. run core test https://github.com/pyodide/pyodide/blob/7cf5bd58095d6484d801cc535b11d60b13412a31/.circleci/config.yml#L158
 - build all packages and run their tests.

So the numpy related errors might actually be a genuine problem because we never run the core test suite with numpy installed.

Generally though you mostly never need to rebuild all packages locally to contribute. Even if you want to add a package you can only build it selectively.  We need to improve contributing docs.

**Comment by albertas** [comment] 2021-05-01 10:51
Tried to run inside docker container:
```
PYODIDE_PACKAGES="micropip,pyparsing,pytz,packaging,kiwisolver" make
tools/pytest_wrapper.py src packages/micropip/ -v -k chrome
```
Almost all tests failed with same reason:
`FAILED test_console.py::console_html[chrome] - conftest.JavascriptException: ReferenceError: _createPyodideModule is not defined`

**Comment by rth** [comment] 2021-05-01 10:54
> ReferenceError: _createPyodideModule is not defined

Yes, I also saw this recently. You need to do a clean rebuild,
```
make clean-all
# commit all your local changes
git clean -xdf  # remove all files not in git
```
then the two above commands.

**Comment by albertas** [comment] 2021-05-01 12:26
Thanks, full clean up helped a little bit, only 7 tests fail now.
```
=============================================================== short test summary info ===============================================================
FAILED test_bz2.py::bz2[chrome]
FAILED test_core_python.py::cpython_core[test_zipfile-chrome] - conftest.JavascriptException: TypeError: Cannot read property 'apply' of undefined
FAILED test_core_python.py::cpython_core[test_zipfile64-chrome] - conftest.JavascriptException: Error: Pyodide already fatally failed and can no lon...
FAILED test_core_python.py::cpython_core[test_zipimport-chrome] - conftest.JavascriptException: Error: Pyodide already fatally failed and can no lon...
FAILED test_core_python.py::cpython_core[test_zipimport_support-chrome] - conftest.JavascriptException: Error: Pyodide already fatally failed and ca...
FAILED test_core_python.py::cpython_core[test_zlib-chrome] - conftest.JavascriptException: Error: Pyodide already fatally failed and can no longer b...
FAILED test_sqlite3.py::sqlite3[chrome]
================================== 7 failed, 554 passed, 8 skipped, 717 deselected, 127 xfailed in 713.67s (0:11:53) ==================================
```

**Comment by rth** [comment] 2021-05-01 12:52
I can confirm that those also fail for me locally.  

`test_zipfile` also fails in CI the first time it's run, but without producing a fatal error at passes when re-run with the pytest wrapper. The other `test_zip*` failures are due to a fatal error in `test_zipfile`.

For `bz2` and `sqlite3`, not sure why they fail locally but not in CI. We need to investigate.

**Comment by rth** [comment] 2022-04-20 21:53
Closing as outdated, as lots of things changed in the last year. For me currently, all tests pass locally as well. If there are other failures we should open a new issue.

**Closed by rth** 2022-04-20 21:53 UTC
