### ISSUE TITLE
Description of all compatible libraries in a readme.md

### ISSUE THREAD

**Issue by LinasNas** [pyodide/pyodide#1672] opened 2021-06-29 18:48 UTC
Hi, 

Would it be useful to have a readme.md file with the title and the description of all libraries that are compatible with Pyodide?

I've compiled the short descriptions of all libraries from their documentation, so I could better understand the capabilities of Pyodide. I could submit a pull request that adds a readme.md file in the folder that contains the names of these packages: https://github.com/pyodide/pyodide/tree/main/packages

**Comment by rth** [comment] 2021-06-29 22:05
If you have a script that can 
 - Add this information to existing `meta.yaml` (possibly by fetching the information from PyPi or conda-forge)
 - Then generate this list automatically  

that would indeed be very useful. We probably wouldn't want to maintain such list manually (in a readme) though. 

Closing as a duplicate of https://github.com/pyodide/pyodide/issues/977, please don't hesitate to comment there.

**Closed by rth** 2021-06-29 22:05 UTC
