### ISSUE TITLE
Out of tree package builds

### ISSUE THREAD

**Issue by hoodmane** [pyodide/pyodide#2390] opened 2022-04-11 17:37 UTC
@ryanking13 has been working recently on making `pip install pyodide-build` actually useful. I think the purpose of this is to eventually enable out of tree builds. What I think we need for this:

### The appropriate version of patched emscripten

We don't really need emccache but it's probably good-to-have. 

### The Python includes. 

They end up in our tree in `cpython/installs/python-3.10.2/include/python3.10/`. Looking at what is in this directory, it's the cpython `Include` directory, plus the generated files `ffi.h`, `ffitarget.h`, and `pyconfig.h`.

### The unisolated packages

If we are out of tree, we should make a new virtual environment and install all unisolated packages into it. Of the unisolated packages, `cffi`, `pycparser`, `pythran`, `cython` are unmodified and can be installed from `pip` as normal, but `numpy` and `scipy` have been injected with modified C and cython headers. I think we could make wheels for the "cross-building" `numpy` and `scipy`.

# How should we get this stuff?

For emscripten, we can just use `emsdk/Makefile`. Maybe make a zip archive with `emsdk/Makefile` and `emsdk/patches`, with `cpython/installs/python-3.10.2/include/python3.10/` and the numpy and scipy wheels and stick this on a server somewhere. If `pyodide-build` detects that it is out of tree, it can download this zip file, run `make -C emsdk`, make a new virtual environment and `pip install cffi pycparser pythran cython` and then install modified numpy and scipy wheels.

**Comment by rth** [comment] 2022-04-11 22:32
I agree that out of tree builds would be a good medium-term goal. The issue is that if we pip install `pyodide-build` and make it download the necessary files and Python packages is not enough (If we do that fetching from git as emsdk does would probably be better I think).  
So far we are building only one system configuration and even something like installing a different version of `patch` can make the build fail. So there are two additional issues,
 -  we need users to `apt install` some dependencies and also install nodejs
 - in the end, few users are on Linux, and we only support Linux currently. So I feel it might be a bit misleading to say that building Pyodide packages is as simple as `pip install pyodide-build && pyodide-build` if it only works on an OS that most users don't use. Trying to fix the build with homebrew or conda  MacOS could help a bit there. 
 
It shouldn't stop us from improving pyodide-build, but something to keep in mind about how we present it in the docs.

**Comment by hoodmane** [comment] 2022-04-11 22:34
Maybe we can replace `patch` and things like it with Python packages. Surely there is a Python package that can apply a patch?

**Comment by rth** [comment] 2022-04-11 23:03
I think it's also linked to the process of making wheels somewhat. Say for manylinux wheels currently one needs to either use the official docker compiler to build locally or use cibuildwheel in CI.  I wouldn't be shocked that to build pyodide wheels one would need to do something comparable. 

It would certainly be better to support diverse build environments if it doesn't require a massive support effort from us. But in the end, I wonder how much that's currently a blocker for adoption. People seem to be building manylinux wheels fine when needed. 

Actually, even standard wheels for MacOS or Windows are a pain to build locally because of the necessity to get the build environment right. It's also not very pleasant to maintain projects where people try to build wheels locally in diverse environments and get all sorts of failures. Hence the popularity of projects like cibuildwheel  (which relies on controlled CI env / Docker) or conda (which ships everything and relies as little as possible on what exists on the host OS). cc @henryiii

Improving pyodide-build further is certainly worthwhile in any case, I'm just wondering what's a reasonable workflow we could confidently support in the end.  For instance, maybe a sufficient cost/benefit approach would be to require docker then pip install pyodide-build and let it interact with Docker in a user-friendly API, I'm not sure.

> Maybe we can replace patch and things like it with Python packages. 

We can't really replace all the Unix build tools with Python packages though :) That's one of the appeals of conda as it allows to install of those dependencies (and compilers) in a cross-platform way, but it's still another tool requirement.

**Comment by hoodmane** [comment] 2022-04-11 23:08
Right. Well if we assume that people will build in a debian docker image, it's a significant improvement if they don't have to build Python or any of Pyodide core. If we could say to use do:
```sh
apt install ....
pip install pyodide-build
python -m pyodide_build buildpkg meta.yaml
```
this would be a significant improvement I think.

**Comment by hoodmane** [comment] 2022-04-11 23:09
The prebuilt docker image is pretty huge, would be good not to need it.

**Comment by ryanking13** [comment] 2022-04-12 10:38
> @ryanking13 has been working recently on making `pip install pyodide-build` actually useful. I think the purpose of this is to eventually enable out of tree builds.

Yes, one of my recent interests is on this topic. Thanks for listing out issues for out-of-tree build. This will be a mid-long-term goal, but I hope we can make it in a gradual way.

> Yes, personally I would be very happy if we could do that, and stop having makefiles as a top level CLI. Related #1977

About the new top-level CLI, my idea is to start with a tiny-thin wrapper of the current `Makefile` and `pyodide-build`, then gradually add more features. I'll make a short design doc about it before next week.

**Comment by rth** [comment] 2022-09-17 08:19
Closing as implemented thanks to all the work by @hoodmane . We can open more specific issues if needed.

**Closed by rth** 2022-09-17 08:19 UTC
