### ISSUE TITLE
Feature Request: Add Google OR-Tools package to Pyodide

### ISSUE THREAD

**Issue by sebastianherreramonterrosa** [pyodide/pyodide#5212] opened 2024-11-19 23:06 UTC
Add support for Google OR-Tools and its solvers in Pyodide to enable optimization and constraint programming capabilities directly in the browser.

Google OR-Tools is a powerful open-source software suite for optimization that includes:

Linear/Mixed-Integer Programming Solvers
Constraint Programming Solver
Vehicle Routing Solver
Graph Algorithms

Currently, these capabilities are not available in browser-based Python environments, limiting the ability to develop web applications that require optimization capabilities.

**Core Components**

- OR-Tools core library
- GLOP (Google's Linear Optimizer)
- CP-SAT solver
- Optional: External solver interfaces (SCIP, GLPK, HIGHS)

**Comment by ryanking13** [comment] 2024-11-20 07:15
PR Welcome

**Comment by agriyakhetarpal** [comment] 2024-11-20 09:04
Hi @sebastianherreramonterrosa, I think this is a duplicate of #5013 and has been attempted, slightly. Could we please continue the discussion there?

**Comment by agriyakhetarpal** [comment] 2024-11-20 09:05
Duplicate of #5013

**Closed by agriyakhetarpal** 2024-11-20 09:05 UTC
Labels: new package request
