### ISSUE TITLE
Install `pyodide-build` in the Docker image

### ISSUE THREAD

**Issue by impermaxvict** [pyodide/pyodide#2708] opened 2022-06-13 20:04 UTC
## Proposed refactoring or deprecation

Please install `pyodide-build` inside of the Pyodide Docker image by adding the following line to the very bottom of the [Dockerfile](https://github.com/pyodide/pyodide/blob/main/Dockerfile):
```Dockerfile
RUN pip install /src/pyodide/pyodide-build
```

### Motivation

The docker image should include all tools for building a simple package (e.g. `sharedlib-test-py`, shown below).
Currently, `pyodide-build` and its dependencies are missing.
This would also pin the version of the dependencies of `pyodide-build` and therefore make the builds more [reproducible](https://reproducible-builds.org/).

### Pitch

See above.

### Additional context

Here is how I build Pyodide packages using [Docker Buildx](https://docs.docker.com/buildx/working-with-buildx/):
<details>
<summary>Click this line to expand</summary>

Note the `--network=none` for packages which do not need to download sources in the Dockerfile.
```Dockerfile
# syntax=docker/dockerfile:1.3
FROM pyodide/pyodide:0.20.0

RUN pip install /src/pyodide/pyodide-build

RUN --network=none \
	useradd --system --user-group --create-home pyodide \
	&& chown -R pyodide:pyodide /src/pyodide/packages/

WORKDIR /src/pyodide/packages/

USER pyodide

RUN --network=none cd sharedlib-test \
	&& python -m pyodide_build buildpkg meta.yaml

RUN --network=none cd sharedlib-test-py \
	&& python -m pyodide_build buildpkg meta.yaml

# ADD --chown=pyodide ./packages/example/ example
# RUN cd example \
#	&& python -m pyodide_build buildpkg meta.yaml

USER root

FROM scratch

COPY --from=0 --chown=root \
	/src/pyodide/packages/sharedlib-test-py/dist/ \
	/build/
```
Run the following command:
```
docker buildx build -o type=tar,dest=build.tar .
```
The wheel of `sharedlib-test-py` can then be found inside of the generated `build.tar` file.
</details>

**Comment by rth** [comment] 2022-06-13 21:21
So we have the pre-built docker image which should install pyodide-build and all dependencies. For the `pyodide-env` image, the issue is that we don't want to release it for each change in `pyodide-build` (or emsdk) or any other other part of the build system.
 It's intended to only provide the environment, to be used in combination with the pyodide repo source tree. 

About build reproducibility, I agree it's an issue. Maybe we should witch to [pip-tools](https://github.com/jazzband/pip-tools) for creating an equivalent of a lock file for Python dependencies.

**Comment by josephrocca** [comment] 2022-06-14 12:04
@rth The pre-built image doesn't come with the Pyodide source unless I've misunderstood something. As stated [here](https://github.com/pyodide/pyodide/blob/main/docs/development/new-packages.md) you need to `git clone` the repo, then run `./run_docker --pre-built`, then `make`, and then `pip install ./pyodide-build`.

I agree that this is burdensome (I opened a [related issue](https://github.com/pyodide/pyodide/issues/2705) yesterday RE ways to avoid the very long `make` build times) and agreed also about the reproducibility. Is it somehow possible for the Docker image come pre-packaged with the source code (which has been pre-`make`-ed)? And for reproducibility, should `meta.yaml` include the Docker image tag? There could be a separate series of Docker tags specifically for reproducible builds?

Or is there some other way to have everything built and ready to go in a Docker image so you can just write `python -m pyodide_build mkpkg <package-name>` right away?

**Comment by josephrocca** [comment] 2022-06-15 05:20
I think @ryanking13 has [discovered the issue](https://github.com/pyodide/pyodide/issues/2705#issuecomment-1155861811) that I was running into:

> Okay... the problem is that we copy all build results into /src/pyodide of prebuilt docker image. But when we use ./run-docker --pre-built we bind local source-tree to /src so /src/pyodide is gone. We have to fix ./run_docker --pre-built behavior...

**Comment by ryanking13** [comment] 2024-06-29 08:19
We are unvendoring pyodide-build from Pyodide (#4882) and after that change, having pyodide-build installed in Pyodide docker image won't make sense. We will automatically install pyodide-build during the build. Closing.

**Closed by ryanking13** 2024-06-29 08:19 UTC
